### ISSUE TITLE
slather on CircleCI not sending to Coveralls 

### ISSUE THREAD

**Issue by gdunnjr** [SlatherOrg/slather#110]
I'm running slather on CircleCI objective-c project.  Slather runs without error and without any output other than:
Slathering...
Slathered.

However, nothing gets sent to Coveralls. I can run slather with coverage --html and that does produce a coverage report on CircleCI

I have set my github repo token in CircleCI Environment Variable: COVERALLS_REPO_TOKEN

.slather.yml:
ci_service: circleci
coverage_service: coveralls
xcodeproj: ObjectiveCBootstrap.xcodeproj
source_directory: ./

circle.yml:
machine:
  xcode:
    version: "7.0"
test:
  override:
    - xcodebuild test -project ObjectiveCBootstrap.xcodeproj -scheme ObjectiveCBootstrap -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.0' ONLY_ACTIVE_ARCH=NO TEST_AFTER_BUILD=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES 
  post:
    - bundle exec slather

**Comment by jasontaft** [comment]
setting the coverage_repo_token in the .slather.xml works, but keeping the token value in an environment variable within CircleCI does not.

**Comment by jasontaft** [comment]
Documentation is wrong; should be COVERAGE_ACCESS_TOKEN instead

**Comment by neonichu** [comment]
Looks like the README has since been updated.
