### ISSUE TITLE
Error when trying to generate a HTML report

### ISSUE THREAD

**Issue by kmargam** [SlatherOrg/slather#111]
Hello Slather team,
I am new to Slather and am trying to set it up for coverage report.
I am using the following branch:
gem 'slather', :git => "https://github.com/mattdelves/slather.git", :branch => "feature-profdata"

I am trying to generate an Html report for my iOS project and used the following command:
"slather coverage --html --show"
and get the following error:
---------
//.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_file.rb:50:in `gcov_data': undefined method `basename' for nil:NilClass (NoMethodError)
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_file.rb:72:in `cleaned_gcov_data'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_file.rb:81:in `line_coverage_data'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_info.rb:5:in `num_lines_tested'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_service/html_output.rb:62:in `block in create_index_html'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_service/html_output.rb:61:in `each'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_service/html_output.rb:61:in `create_index_html'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_service/html_output.rb:41:in `create_html_reports'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/lib/slather/coverage_service/html_output.rb:19:in `post'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/bin/slather:80:in `post'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/bin/slather:46:in `execute'
	from //.rvm/gems/ruby-2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from //.rvm/gems/ruby-2.1.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from //.rvm/gems/ruby-2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from //.rvm/gems/ruby-2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from //.rvm/gems/ruby-2.1.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from //.rvm/gems/ruby-2.1.0/bundler/gems/slather-d09ce4f5d592/bin/slather:6:in `<top (required)>'
	from //.rvm/gems/ruby-2.1.0/bin/slather:23:in `load'
	from //.rvm/gems/ruby-2.1.0/bin/slather:23:in `<main>'
	from //.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from //.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

Can some one please advice on what i am doing wrong?

Thank you

**Comment by Pavan-Concur** [comment]
i am facing the same issue. mine is a new swift 2.0 project with Xcode 7

**Comment by kylejm** [comment]
I'm getting this too with Swift 2.0 and Xcode 7. Is Slather dead?

**Comment by kylejm** [comment]
Actually mine's a little different to this. I get the following:

```

**Comment by kylejm** [comment]
Strange that this option has been removed but the README still says you can use it.

After running `slather coverage Loot.xcodeproj/` I get this error:

```
Slathering...
/Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/slather-1.8.2/lib/slather/project.rb:49:in `coverage_files': No coverage files found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.pbxproj` (StandardError)
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/slather-1.8.2/lib/slather/coverage_service/simple_output.rb:13:in `post'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/slather-1.8.2/bin/slather:56:in `post'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/slather-1.8.2/bin/slather:32:in `execute'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Users/kylejm/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/slather-1.8.2/bin/slather:6:in `<top (required)>'
	from /Users/kylejm/.rbenv/versions/2.2.0/bin/slather:23:in `load'
	from /Users/kylejm/.rbenv/versions/2.2.0/bin/slather:23:in `<main>'
```

I have already done `slather setup Loot.xcodeproj`, so I don't understand why this is happening.

**Comment by kylejm** [comment]
Maybe this is the cause

https://github.com/venmo/slather/blob/a95d83ee64d76a72350acbc47483820ff56a86b1/lib/slather/coverage_file.rb#L14

**Comment by neonichu** [comment]
The `master` branch supports profdata now, there'll be a new release soon.
