### ISSUE TITLE
Release 1.8.2 on rubygems.org

### ISSUE THREAD

**Issue by pietbrauer** [SlatherOrg/slather#113]
Could someone please `gem push slather.gem`? It seems it is not available on rubygems.org: https://rubygems.org/gems/slather

Thanks!

**Comment by chaitanyakuber** [comment]
:+1: To the above request. This causing some major issues in various build pipelines.

**Comment by dbworku** [comment]
+1

**Comment by Ashton-W** [comment]
@ayanonagon are you able to publish the latest version to rubygems.org?

**Comment by ayanonagon** [comment]
Yes. Learning how to publish Ruby gems right now, but should be up within the hour. :dancers:

**Comment by ayanonagon** [comment]
Done. Let me know if I messed up. :grimacing:

**Comment by Ashton-W** [comment]
@ayanonagon I think there is a problem with the gem on rubygems :(

Some coverage options aren't working anymore, but they work if I build the `1.8.2` tag from source.
Also the output of `coverage --help` is different and has a bunch of stuff missing and mislabled`.

```
$ gem install slather --version 1.8.2
$ slather coverage --help
Usage:
    slather coverage [OPTIONS] [xcodeproj]

Parameters:
    [xcodeproj]                   Path to the xcodeproj

Options:
    --travis, -t                  Indicate that the builds are running on Travis CI
    --coveralls, -c               Post coverage results to coveralls
    --simple-output, -s           Post coverage results to coveralls
    --build-directory, -b BUILD_DIRECTORY The directory where gcno files will be written to. Defaults to derived data.
    --source-directory SOURCE_DIRECTORY The directory where your source files are located.
    --ignore, -i IGNORE           ignore files conforming to a path
    -h, --help                    print help
```

The output from a locally built slather:
```
Usage:
    slather coverage [OPTIONS] [xcodeproj]

Parameters:
    [xcodeproj]                   Path to the xcodeproj

Options:
    --travis, -t                  Indicate that the builds are running on Travis CI
    --circleci                    Indicate that the builds are running on CircleCI
    --jenkins                     Indicate that the builds are running on Jenkins
    --buildkite                   Indicate that the builds are running on Buildkite
    --coveralls, -c               Post coverage results to coveralls
    --simple-output, -s           Output coverage results to the terminal
    --gutter-json, -g             Output coverage results as Gutter JSON format
    --cobertura-xml, -x           Output coverage results as Cobertura XML format
    --html                        Output coverage results as static html pages
    --show                        Indicate that the static html pages will open automatically
    --build-directory, -b BUILD_DIRECTORY The directory where gcno files will be written to. Defaults to derived data.
    --source-directory SOURCE_DIRECTORY The directory where your source files are located.
    --output-directory OUTPUT_DIRECTORY The directory where your Cobertura XML report will be written to.
    --ignore, -i IGNORE           ignore files conforming to a path
    -h, --help                    print help
```

`1.8.2` on RubyGems have been built from different source, right?
I've tested this on two machines.

**Comment by ayanonagon** [comment]
@Ashton-W Yikes, sorry about that! This is what happens when someone who doesn’t know much about Ruby does a release (aka me). :sleepy: All I did was run `rake release` from latest master, which is supposed to `# Create tag v1.8.2 and build and push slather-1.8.2.gem to Rubygems`. Please let me know how I can fix this. :pray: Thanks!

**Comment by Ashton-W** [comment]
Not sure what could of gone wrong. All I can think of is your working copy must have had changes?

Try a new clone, checkout `v1.8.2`.
Run `rake install`, then try out the gem `slather coverage --help`, output should be the full one I posted above.
Release again. Not sure if RubyGems will let you release `1.8.2` again, so we might have to release `1.8.3`

**Comment by tamastimar** [comment]
@ayanonagon Once there is a new working release it seems you can remove the broken gem version by running `gem yank GEM -v VERSION`.

See here: http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem

**Comment by marklarr** [comment]
1.8.2 has been yanked and 1.8.3 has been pushed, which should be the right code. Try it out!

**Comment by Ashton-W** [comment]
Looks good, thanks!
