### ISSUE TITLE
Slather Breaks Bitcode

### ISSUE THREAD

**Issue by calebd** [SlatherOrg/slather#115]
Just thought I would post this here and see if there is a good solution. The build settings required by Slather break Bitcode. Related: https://github.com/soffes/RateLimit/issues/18.

**Comment by calebd** [comment]
I suppose you could recommend that people only enable the two required build settings in a debug configuration which the test phase of a scheme targets by default.

**Comment by neonichu** [comment]
This is basically a duplicate of #73
