### ISSUE TITLE
Is there a way to specify the location of DerivedData?

### ISSUE THREAD

**Issue by Vaseltior** [SlatherOrg/slather#121]
Hi,

Considering that I choosed to use relative location of DerivedData to prevent interferences of compilation through different projects, I'm not seeing somewhere where I could tell to use a specific DerivedDara location for Slather to find the gcov files.

Am I missing something or the path to the DerivedData directory is static?

**Comment by gretzki** [comment]
Hi,

I'm also configuring xcode to use a specific path `build` for derived data.
When invoking slather you can use the `build-directory` parameter:
`slather coverage --build-directory build/`

Cheers,
Chris

**Comment by Vaseltior** [comment]
Ok, thank you, this was the answer I was looking for, even if, I admit, it is not the right place for asking such a question.
