### ISSUE TITLE
html report coloring missed lines as covered

### ISSUE THREAD

**Issue by cutz** [SlatherOrg/slather#122]
On master I am seeing a problem where the html report is styling missed lines as though they have been covered (green).  I expect missed lines would be styled as red.  I've attached a trivial project demonstrating this behavior.  Enable coverage and run the unit tests for the attached project [SlatherHTMLReport.zip](https://github.com/venmo/slather/files/96783/SlatherHTMLReport.zip). Then run slather on the output like so:

`slather coverage --html --show --scheme SlatherHTMLReport SlatherHTMLReport SlatherHTMLReport.xcodeproj/`

The results can be seen in [html.zip](https://github.com/venmo/slather/files/96784/html.zip).  Notice the body of addTwo: is styled as though it has been covered when in actuality it is a miss.

**Comment by cutz** [comment]
I've been trying to track down the actually problem.  Admittedly my ruby is weak but I think this may stem from a change in the coverage file format between the profdata format that had support by way of #92 merged in recently and the older gcov coverage format.  The implementation of `class_for_coverage_data` in html_output.rb along with the tests in `coverage_file_spec.rb` and `profdata_coverage_spec.rb` suggest that the old coverage data notated missed lines with `####` where as the the profdata format results in coverage data that notates missed lines with `0`.

This discrepancy seems to cause issues with the current implementation of html_output.rb.  While it seems like an easy enough patch to that reporter, I find myself wondering what sorts of issues this inconsistency may cause with other output types.

**Comment by neonichu** [comment]
Fixed by #124
