### ISSUE TITLE
Xcode 7.3 changes location of Coverage.profdata

### ISSUE THREAD

**Issue by raven** [SlatherOrg/slather#125]
Xcode 7.2 would place Coverage.profdata within
`#{build_directory}/**/CodeCoverage/#{self.scheme}/`

However in 7.3, Coverage.profdata doesn't get nested within a directory matching the scheme name. 
`#{build_directory}/**/CodeCoverage/`

**Comment by neonichu** [comment]
Can't actually repro slather not finding the profdata files with 7.3 beta 2. However, coverage information is also not computed correctly for me. 

I'm descoping this from 2.0.0 since it needs more investigation and 7.3 is still in beta.

**Comment by manuyavuz** [comment]
Seems like in Xcode 7.3 (I'm using beta 4 now), `Coverage.profdata` file inside `Build/Intermediates/CodeCoverage/` folder is being overwritten by the last run in the Xcode regardless of the scheme to be tested. In Xcode 7.2, all schemes was having different `Coverage.profdata` files inside their corresponding subdirectory `Build/Intermediates/CodeCoverage/#{scheme_name}`.

This causes both `--scheme` option and the default scenario (slather finding path using `.app` dropped product name).

**Comment by manuyavuz** [comment]
I could make it work again by changing the following line [here:](https://github.com/SlatherOrg/slather/blob/3b67948e567009eb04bda585c91d5ae4c67c11c5/lib/slather/project.rb#L120)

`dir = Dir[File.join("#{build_directory}","/**/#{first_product_name}")].first`

to below line:

`dir = Dir[File.join("#{build_directory}","/**/CodeCoverage")].first`

But I'm not sure how this can be changed providing backward compatibility.

**Comment by neonichu** [comment]
I think a reasonable way to deal with this could be checking the Xcode version explicitly, like

```bash
$ xcodebuild -version
Xcode 6.4```

And if that is 7.3 or higher, use the new path. This wouldn't be 100% accurate, as the selected Xcode version isn't necessarily the one used to do the last run for a certain project, but since CI is the most common use case, it should be OK.

**Comment by mapedd** [comment]
TIL: there is an env var now that points to exact path of Coverage.profdata file: 

```
CLANG_COVERAGE_PROFILE_FILE
```
