### ISSUE TITLE
Ignore files having relative paths like `../../../../../../Applications/Xcode-beta.app/`

### ISSUE THREAD

**Issue by manuyavuz** [SlatherOrg/slather#129]
Hi, 

I'm trying to generate coverage report using profdata format. It generates coverage reports for files like this:

```
../../../../../../Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFString.h: 0 of 1 lines (0.00%)
../../../../../../Applications/Xcode-beta.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h: 0 of 1 lines (0.00%)
```

However, I couldn't find a way to ignore them via --ignore option because it does not accept regular expressions and expects relative paths.

I can ignore them  using `--ignore ../../../../../../Applications/**'' option, but this is definitely not good because whenever I change the path of my project this will fail.

Is there a specific reasoning behind not using regular expressions to ignore files?

**Comment by HeEAaD** [comment]
We're using `--ignore '../*'`, maybe it helps.

**Comment by manuyavuz** [comment]
@HeEAaD thanks for the suggestion, it worked for that scenario.

However, I'd much prefer to have a `--include` option and be able to specify only paths to be included to coverage calculation.

Is the team OK with that kind of change? If so, I can send a PR for that feature.

**Comment by neonichu** [comment]
#128 is basically going in that direction

**Comment by yakimant** [comment]
Vote for `--include` option also!

**Comment by yakimant** [comment]
@neonichu, how #128 can be used for paths include list?
Thank you!

**Comment by neonichu** [comment]
@yakimant 🤔 — in retrospect, my comment doesn't make much sense :)

**Comment by yakimant** [comment]
@neonichu, can I make a create a new issue/feature then?

**Comment by neonichu** [comment]
This issue is still open.

**Comment by eikebartels** [comment]
After I added  `../* `  to my ".slather.yml"

`ignore:
  - ../*
  - Pods/*`

Travis tells me 

> No output has been received in the last 10m0s

**Comment by eikebartels** [comment]
Ok. Sometime it works and sometimes not. Probably the connection between coveralls and Travis 
Any idea how to improve the performance?

**Comment by neonichu** [comment]
Travis has had some major issues with their OS X infra the last few days, probably best to test again next week and see if this was related.
