### ISSUE TITLE
Slather HTML reports not self contained

### ISSUE THREAD

**Issue by colincornaby** [SlatherOrg/slather#136]
If I generate HTML from Slather it's not self contained. I.E. if I move it to another machine without Slather installed the HTML no longer renders properly. It looks like it's referencing CSS and images from the locally installed copy of Slather instead of copying them into the HTML package.

This is a serious issue for uploading reports to web servers where other developers can see them.

A pull request was accidentally opened by another developer that patches this issue, but closed:
https://github.com/SlatherOrg/slather/pull/130

**Comment by colincornaby** [comment]
I've written a pull request #137 for this

**Comment by neonichu** [comment]
Fixed by #137
