### ISSUE TITLE
Slather can't generate stat

### ISSUE THREAD

**Issue by bimawa** [SlatherOrg/slather#142]
Guys hi! I setup project liek tall in readme. But `slather` throw me next messages:

```
Slathering...
error: Failed to load coverage: No coverage data found
Test Coverage: NaN%
Slathered
```
What's i do wrong?

**Comment by neonichu** [comment]
Which version of Xcode/Slather are you using? Version 2.0.0 has a `--verbose` option to get some more info.

**Comment by PaulTaykalo** [comment]
This happened to me when I incorrectly specified derived data path

**Comment by bimawa** [comment]
I have two xcode 6 and 7.2 and `slather` show to me two different paths:

```
Slathering...

Processing coverage file: /Users/[username]/Library/Developer/Xcode/DerivedData/TCProject-iOS-adthsccwxmcojceexkceyprsrjuz/Build/Intermediates/CodeCoverage/All in Tests/Coverage.profdata
Against binary file: /Users/[username]/Library/Developer/Xcode/DerivedData/Events-bpmcndrhjepltngcrskkdxbfyfstk/Build/Products/Debug-iphonesimulator/Events.app/Events
``` 
Strangely  why it get two different path. Now i go try clear Derived data folder....

**Comment by bimawa** [comment]
@neonichu thx u for verbose key, all worked now.

**Comment by alexcosmin** [comment]
@bimawa How did you fix the issue?
I'm also getting the same:

```
Slathering...

Processing coverage file: 
/Users/SomeUser/Library/Developer/Xcode/DerivedData/SomeProject-gawgzecgjjpjmlabcprvqowfmryo/Build/Intermediates/CodeCoverage/Coverage.profdata
Against binary file: 
/Users/SomeUser/Library/Developer/Xcode/DerivedData/SomeProject-gawgzecgjjpjmlabcprvqowfmryo/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/SomeProject.app/PlugIns/SomeProject Tests.xctest/SomeProject Tests

[0;31merror: Failed to load coverage: No coverage data found[0m
Slathered
```

I'm using Xcode 7.3. Any idea how to fix that? I guess it has to be the same path.

**Comment by bimawa** [comment]
@alexcosmin hi just `rm -rf DerivedData`

**Comment by alexcosmin** [comment]
@bimawa I already tried deleting the derived data. Still have the same issue.
Any other suggestions? Thanks for the super quick reply.

**Comment by bimawa** [comment]
1. You clean project
2. You must be sure for checked 
![screen shot 2016-03-29 at 18 22 20](https://cloud.githubusercontent.com/assets/1393809/14109431/62885782-f5db-11e5-9768-0462fbf3d8d3.png)

3. launch tests
4. and Slather detect my coverages in DerivedData.

I'm don't know addition information sry :( I'ts just start work and all.

**Comment by rishabdutta** [comment]
@bimawa Same here. Cleaning works I guess.
