### ISSUE TITLE
Wrong binary being used

### ISSUE THREAD

**Issue by marcelofabri** [SlatherOrg/slather#144]
I'm trying to setup Slather on my project, but it seems that the wrong binary is being used:

```
slather coverage -s --verbose Centre.xcodeproj               
Slathering...

Processing coverage file: /Users/marcelofabri/Library/Developer/Xcode/DerivedData/Centre-fecmhscriwkgwegihvmduhowgzbh/Build/Intermediates/CodeCoverage/UK Development/Coverage.profdata
Against binary file: /Users/marcelofabri/Library/Developer/Xcode/DerivedData/BigBrother-aqpuxuzsaupzgthkmtqsxcovqupe/Build/Intermediates/SwiftMigration/BigBrother/Products/Debug-iphonesimulator/BigBrother.framework/BigBrother

error: Failed to load coverage: No such file or directory
Test Coverage: NaN%
Slathered
```

The coverage file is the right one (and exists). Also, code coverage works on Xcode. I'm using the latest Slather version (2.0.0) and Xcode 7.2.1.

**Comment by neonichu** [comment]
By default, slather will pick the first binary it finds alphabetically for code coverage. If you want a different one to be used, the `--binary-basename` or `--binary-file` will be of use.

**Comment by marcelofabri** [comment]
For some reason, passing `--scheme` resolved the issue.

**Comment by neonichu** [comment]
If multiple schemes are used, slather can also end up looking into the wrong one when trying to find binaries for code coverage.

**Comment by marcelofabri** [comment]
I do have multiple schemes, but the weird thing is that another app binary (or even a framework) was used.

**Comment by neonichu** [comment]
Might also be related to #145
