### ISSUE TITLE
What support is offered for Xcode UITests targets?

### ISSUE THREAD

**Issue by kdawgwilk** [SlatherOrg/slather#151]
I have found that the support for UITest targets is somewhat lacking.  I believe this could be due to Xcode producing two different .app binaries.  One is the actual app and the other is a proxy where UI tests interact with the app.  Slather seems to get confused on which binary should be used when processing the profdata file.  Can this be solved by telling slather specifically to use a certain binary? and if so which one should it be?

**Comment by neonichu** [comment]
I don't have any experience myself with UITests, but I think choosing the actual app binary using the `—binary_basename` or `—binary_file` options should work.

**Comment by kdawgwilk** [comment]
Related to the error being produced in #153

**Comment by kdawgwilk** [comment]
I am no longer using Slather
