### ISSUE TITLE
Are workspaces supported

### ISSUE THREAD

**Issue by tspecht** [SlatherOrg/slather#153]
Hi guys,

are workspaces supported with slather?

**Comment by neonichu** [comment]
Workspaces are not supported as a CLI argument, but whether or not you are using a workspace to build your project doesn't matter to slather.

**Comment by tspecht** [comment]
Hmm any idea then why I'm not able to use it?

Fabfile:
```
xctool :test, [
      '-workspace', 'MyProject.xcworkspace',
      '-scheme', 'MyProjectTests',
      '-sdk', 'iphonesimulator'
    ]

     slather(
      scheme: 'MyProjectTests',
      proj: 'MyProject.xcodeproj'
    )
```

The error simply says
```
`find_binary_file': No product binary found in /Users/myUser/Library/Developer/Xcode/DerivedData/MyProject-feagzyrzafumrqfimizbpaeyingz/Build/Intermediates/CodeCoverage/MyProjectTests. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj
```

I already executed the setup command and it simply finished with no output

**Comment by kdawgwilk** [comment]
I believe this is due to your binary filename differing from your scheme name. In your case you will also need to pass the binary name explicitly because slather makes some assumptions based on your scheme name.
```ruby
slather(
      binary_basename: 'MyProject'
      scheme: 'MyProjectTests',
      proj: 'MyProject.xcodeproj'
    )
```
