### ISSUE TITLE
Ignore more than one path command line

### ISSUE THREAD

**Issue by iuri-matsuura** [SlatherOrg/slather#155]
Is it possible to use the "ignore" parameter passing more than one argument in the command line?

For instance:

`slather coverage -i path1 path2`

When I try to do this I get an error "Too many arguments" and I saw that the parameter is multivalued.

Thanks in advance.

**Comment by neonichu** [comment]
The argument parsing is bit horrible, I *think* `slather coverage -i path1 -i path2` might be the way to do it.

**Comment by iuri-matsuura** [comment]
Hi @neonichu,

It worked! Thanks for the quickly reply.

**Comment by lemonkey** [comment]
I'm seeing some issues with this, especially when a pattern based source_files parameter is used from the command line. Within a .slather.yml it's fine however.
