### ISSUE TITLE
Incomplete Code Coverage Information After Renaming Project

### ISSUE THREAD

**Issue by cosminstirbu** [SlatherOrg/slather#156]
Hi,

I have been using Slather for a while now to generate code coverage using the .profdata input.
It has been generating the correct code coverage for all my source files.

We had to rename our project and we successfully did so. The project builds, it runs the unit tests, from both GUI and using xcodebuild using Jenkins.

The problem is that now the exact same slather script that we used to generate the code coverage before is now generating the code coverage for a single file which is from a pod, not even from our own source code.

In Xcode, if I go to the GUI and I check the generated code coverage, the code coverage generated is correct, so no changes since we have renamed the project.

I am really out of ideas, I have compared the .profdata files, they are the same size, so nothing changed there.

I have searched the whole project for references using the previous name and even the build & derived data folders, and I didn't find any.
I have even tried created a new target / scheme, and I still get the same issue.

Is there maybe some weird caching that slather does, or do you have any other suggestions?
The issue reproduces both on my machine and also on our Jenkins build server.

This is the script that I'm using:

```
SCHEME="$1"
PROJECT="$2"
BUILD_DIRECTORY="$3"
FORMAT="$4"


if [ -z "${FORMAT}" -o -z "${SCHEME}"  -o -z "${SCHEME}"  -o -z "${PROJECT}" ]; then
    echo "usage: slather.sh SCHEME PROJECT BUILD_DIRECTORY cobertura-xml|simple-output|html"
    exit 2
fi

bin/slather coverage \
    --input-format profdata \
    --${FORMAT} \
    --ignore "../**/*/Xcode*" \
    --output-directory slather-report \
    --scheme ${SCHEME} \
    --build-directory ${BUILD_DIRECTORY} \
    ${PROJECT}
```
Obviously I am passing the new update parameters according to the project rename.

Any kind of help would be highly appreciated.
Thank you.

**Comment by neonichu** [comment]
Slather picks the first binary file it finds for the given DerivedData directory, so most probably you just were lucky initially with your naming. See the help for options to pick a specific binary:

```
   --binary-file BINARY_FILE     The binary file against the which the coverage will be run
    --binary-basename BINARY_BASENAME Basename of the file against which the coverage will be run
``

**Comment by cosminstirbu** [comment]
You've saved me.
Using --binary-basename worked.
I've spend 3 hours looking into this. Should've read the documentation ...

Thank you!

**Comment by thejaa** [comment]
Hi @cosminstirbu @neonichu 
I am also facing the same issue.

Can you please share where I need to change --binary-basename.
