### ISSUE TITLE
Support Multiple Binary Files

### ISSUE THREAD

**Issue by mikelikespie** [SlatherOrg/slather#157]
Our swift project has several dynamic libraries. When running UI tests, we exercise functionality in several of them.

It appears that slather requires one invocation per binary file at the moment. (or one .slather.yml per binary file).

Is there a way to produce coverage reports for a list of binary files or is this something that will have to be scripted?

**Comment by ksuther** [comment]
I'm currently scripting slather with something like this:

```
#!/bin/bash

coverage_binaries=("A" "B" "C" "D" "E")

for binary_name in "${coverage_binaries[@]}"; do
    /usr/local/bin/slather coverage --scheme MyScheme --binary-basename "$binary_name" --cobertura-xml --output-directory build/coverage -i '../*' MyProject.xcodeproj
    mv build/coverage/cobertura.xml "build/coverage/$binary_name.xml"
done
```
