### ISSUE TITLE
Combining results from multiple schemes

### ISSUE THREAD

**Issue by brockboland** [SlatherOrg/slather#159]
We might be using an odd setup, but I'm trying to figure out if there's a way to combine the coverage results from two separate test runs into a single `cobertura.xml` output.

- Two test targets: one for unit tests, one for UI tests
- Two schemes: one for each test target
- UI tests run, then unit tests

When I run things this way (from fastlane, anyway), slather reports on the coverage of the unit tests only—that is, the set of tests that ran last. Which means, in this case, that I'm seeing 0% coverage on the views, view controllers, etc.

Is there a way to have slather handle coverage for multiple schemes at once? Or would I be better off just adding a third scheme that runs both test targets, and use that when checking code coverage?

**Comment by neonichu** [comment]
Slather can't currently handle more than one scheme in one run.

**Comment by brockboland** [comment]
Got it, thanks.

**Comment by kmalyshev** [comment]
Since Apple introduced test plans and I don't see how to run all of them in the same target (if there are multiple test plans) we return to the same problem. Any updates on that feature? Seems to be useful.

**Comment by tedgonzalez** [comment]
+1
