### ISSUE TITLE
Coverage coverage files from cocoa pod source files

### ISSUE THREAD

**Issue by ryang1428** [SlatherOrg/slather#160]
I apologize if this has been brought up, I scoured through any similar issues I could find for a solution.

I have a cocoa pod that contains models. I want my Jenkins server to show the coverage using slather. I got my pod generating code coverage for the pods source files, not just the example, but when I run the slather command, it is only looking at the coverage file for the example app. 

![](http://f.cl.ly/items/1e1Z302R1g373i0i020S/Screen%20Shot%202016-03-03%20at%203.52.11%20PM.png)

In the screenshot above, You can see the different coverages my pod is generating. I then call `slather coverage`, which successfully goes through, BUT on jenkins it is only looking at the coverage in the `Example.app`, but I want it to look at the `URBNModels.framework` coverage. I messed around with the `--source-directory`, but I could not get that working, nor could I find where the `URBNModels.framework` coverage file is being placed in my derived data.

Any assistance would be appreciated! Thanks!

**Comment by neonichu** [comment]
The `--binary-file` or `--binary-basename` options should do the trick to select the binary you want coverage for.
