### ISSUE TITLE
Slather 2.0.1 cannot find binary (2.0.0 can)

### ISSUE THREAD

**Issue by cfedak** [SlatherOrg/slather#162]
The error I'm seeing in 2.0.1 is:

slather-2.0.1/lib/slather/project.rb:290:in `find_binary_file': No product binary found in ./Build/Intermediates/CodeCoverage/blob - No UI Tests/Products/Debug-iphonesimulator/Blob.app/Blob
/Users/cfedak/.gems/ruby/2.2.0/slather-2.0.1/lib/slather/project.rb:282:in `configure_binary_file'

In 2.0.0, slather works perfectly with the same project.  I'm using fastlane to build, and my scan/slather command looks like this:

scan(
      scheme:'blob - No UI Tests',
      output_directory:'Build/reports',
      output_types:'html, junit',
      derived_data_path:'./Build',
      code_coverage: true)
slather(
      proj:'blob.xcodeproj',
      ignore: ['Pods/*', '../*'],
      build_directory:'./Build',
      output_directory:'Build/reports/coverage',
      html: true)

I've also verified that the project is setup correctly (manually, and using slather setup) with no change in outcome.

**Comment by Conaaando** [comment]
I can confirm this in my end. Just uninstalled 2.0.1 and BANG! Binary was found.

Xcode version 7.2.1, OS X 10.11.3

Here is my .slather file:

```
coverage_service: cobertura_xml
xcodeproj: ProjectName.xcodeproj
source_directory: ProjectName
output_directory: build/slather-report
ignore:
  - ProjectName/Model/Datamodel/*
  - ProjectName/Controller/*
  - ProjectName/View/*
  - ProjectName/Helpers/*
  - ProjectName/Supporting Files/*
```

**Comment by neonichu** [comment]
Should be fixed by https://github.com/SlatherOrg/slather/releases/tag/v2.1.0 — please let us know if it is not.
