### ISSUE TITLE
No product binary found 

### ISSUE THREAD

**Issue by wangtao169447** [SlatherOrg/slather#164]
when i run the script "slather coverage -s path/to/project.xcodeproj",I meet the follow problem.

/Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:290:in `find_binary_file': No product binary found in /Users/MyUser/Library/Developer/Xcode/DerivedData/AppName-cgtfzgzjmzrazefbtspivwirgaeo/Build/Intermediates/CodeCoverage/AppName Debug. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
    from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:282:in `configure_binary_file'
    from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:199:in `configure'
    from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:52:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
    from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:6:in `<top (required)>'
    from /usr/local/bin/slather:23:in `load'
    from /usr/local/bin/slather:23:in `<main>'

I did the follow ways, but it did not work .
1.deleting the DerivedData directory
2.in Slather-x.x.x/lib/slather/project.rg -> def profdata_coverage_dir do this:

     dir = Dir[File.join("#{build_directory}","/**/CodeCoverage/#{self.scheme}")].first
      # if self.scheme
      #   dir = Dir[File.join("#{build_directory}","/**/CodeCoverage/#{self.scheme}")].first
      # else
      #   dir = Dir[File.join("#{build_directory}","/**/#{first_product_name}")].first
      # end

**Comment by neonichu** [comment]
Should be fixed by https://github.com/SlatherOrg/slather/releases/tag/v2.1.0 — please let us know if it is not.
