### ISSUE TITLE
Intermittent issues reading xcodeproj files

### ISSUE THREAD

**Issue by TeresaP** [SlatherOrg/slather#165]
Occasionally I see this in the logs. Is there a known workaround?

```
+ slather coverage --jenkins --input-format profdata --scheme Redacted-cov --html --ignore '../**/*/Xcode*' --output-directory /Users/dpbuild/Jenkins/workspace/<workspace-redacted>/CodeCoverage/html_results/project_name-redacted /Users/dpbuild/Jenkins/workspace/<workspace-redacted>/CodeCoverage/cobertura_xml_results/project_name-redacted.xcodeproj
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:64:in `read': Xcodeproj::Informative
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/plist_helper.rb:13:in `read_plist'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:193:in `initialize_from_file'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.28.2/lib/xcodeproj/project.rb:95:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:59:in `open'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:95:in `project'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:81:in `setup_service_name'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:40:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:6:in `<top (required)>'
	from /usr/bin/slather:23:in `load'
	from /usr/bin/slather:23:in `<main>'
```

**Comment by neonichu** [comment]
Haven't seen this one before and the stacktrace suggests that the project file itself doesn't exist when a reading attempt occurs. Could this be a race condition in whatever part of your CI setup actually copies/fetches the project file?

**Comment by TeresaP** [comment]
I don't believe so. I can see the file after the run completes. This is the code that calls slather:

for xcproj in $(find "${WORKSPACE}" -path "*.xcodeproj"); do
   base_file_name=$(basename "${xcproj}")
   base_file_name=${base_file_name%.*}
   slather coverage --jenkins --input-format profdata --scheme "${SCHEMA}" --html --ignore "../**/*/Xcode*" --output-directory "${WORKSPACE}/CodeCoverage/html_results/${base_file_name}" "${xcproj}"
   slather coverage --jenkins --input-format profdata --scheme "${SCHEMA}" --cobertura-xml --ignore "../**/*/Xcode*" --output-directory "${WORKSPACE}/CodeCoverage/cobertura_xml_results/${base_file_name}" "${xcproj}"
done

**Comment by TeresaP** [comment]
Let me dig around a bit

**Comment by TeresaP** [comment]
Looks like my loop that was looking for xcodeproj files was finding some bad folders (which were not projects, but were named like them) leftover from a previous run
