### ISSUE TITLE
No binary found...

### ISSUE THREAD

**Issue by chriswunsch00** [SlatherOrg/slather#171]
Manually installed latest commit as local gem due to team city support not being in the public gem, perhaps the gem needs updating ?

Getting:

Slathering...
/Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:296:in `find_binary_file': No product binary found in /Users/ChrisWunsch/Library/Developer/Xcode/DerivedData/Paragon-brrarwnrtodrirazaytsdwlzjork/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Paragon.app/Paragon. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:287:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:204:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:53:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/bin/slather:6:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'

Any clues about this ? Was working a few days ago, suspect this is a very latest Xcode release issue ?

**Comment by themackworth** [comment]
You can use a Gemfile like this:

1)Install bundler
2) Create a Gemfile that contains `gem 'slather', :git => 'git://github.com/SlatherOrg/slather', ref: 'f4d2e3b'`
3) run `bundle install`
4) run slather by running `bundle exec slather ...`

**Comment by neonichu** [comment]
Should be fixed by https://github.com/SlatherOrg/slather/releases/tag/v2.1.0 — please let us know if it is not.
