### ISSUE TITLE
`profdata_coverage_dir': No coverage directory found. Xcode 7.3

### ISSUE THREAD

**Issue by janiduw** [SlatherOrg/slather#175]
I've been using Slather for awhile with Xcode 7.2.1 with no issues. However after updating to Xcode 7.3 I noticed that coverage data is not accurate. I updated slather to the latest version (2.0.2) and now I'm getting the following error. I tried deleting the DerivedData folder as well. Still no luck

```
/Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:144:in `profdata_coverage_dir': No coverage directory found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:310:in `find_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:288:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:205:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/command/coverage_command.rb:43:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
```

**Comment by ksuther** [comment]
What's your slather command or config look like? Are you specifying a scheme explicitly?

**Comment by janiduw** [comment]
Yes I'm specifying a scheme explicitly.

`slather coverage --verbose --scheme My_Project --html --output-directory fastlane/slather_output My_Project.xcodeproj`

**Comment by ksuther** [comment]
What's the path of your CodeCoverage directory inside of DerivedData? That errors occurs because slather can't find a CodeCoverage directory inside of your DerivedData path. Are you running the tests through Xcode or with xcodebuild and using custom parameters?

**Comment by janiduw** [comment]
I was initially running my tests using fastlane/scan and I was executing slather using fastlane's slather plugin. However to isolate this problem, currently I'm running the tests through Xcode and then executing slather using the command that I've given earlier. 

Path of the coverage directory
` /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-fbuvvqycdpxwjtaibtdxnwmvdxqc/Build/Intermediates/CodeCoverage/Coverage.profdata`

I've noticed something weird when I execute slather, that it creates another derived data folder and this folder does not contain a coverage folder.

`/Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-bkhkhcmsrfudevddfruxceraajga`

**Comment by ksuther** [comment]
What's the output of `xcodebuild -project YourProject.xcodeproj -scheme YourScheme -showBuildSettings | grep " OBJROOT"`?

slather looks for the CodeCoverage directory by searching recursively within OBJROOT.

**Comment by janiduw** [comment]
`OBJROOT = /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-bkhkhcmsrfudevddfruxceraajga/Build/Intermediates`

Seems its getting the folder without the coverage information

**Comment by ksuther** [comment]
Are you using two different build configurations, such as Debug/Release? I'm not sure why Xcode would be switching between different derived data prefixes. Maybe try `xcodebuild -project YourProject.xcodeproj -scheme YourScheme -configuration Debug -showBuildSettings | grep " OBJROOT"` and `xcodebuild -project YourProject.xcodeproj -scheme YourScheme -configuration Release -showBuildSettings | grep " OBJROOT"`?

**Comment by janiduw** [comment]
Yes there are two configurations Debug and Release in my Scheme

```
xcodebuild -project My_Project.xcodeproj -scheme My_Project -configuration Debug -showBuildSettings | grep " OBJROOT"
OBJROOT = /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-bkhkhcmsrfudevddfruxceraajga/Build/Intermediates

xcodebuild -project My_Project.xcodeproj -scheme My_Project -configuration Release -showBuildSettings | grep " OBJROOT"
OBJROOT = /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-bkhkhcmsrfudevddfruxceraajga/Build/Intermediates

```

**Comment by ksuther** [comment]
Well that's puzzling. I'm not sure where that other derived data hash is coming from.

What happens if you run `xcodebuild -project YourProject.xcodeproj -scheme YourScheme test`? Does it put CodeCoverage in `bkhkhcmsrfudevddfruxceraajga` or `fbuvvqycdpxwjtaibtdxnwmvdxqc`?

**Comment by janiduw** [comment]
Sorry but that command does not succeed because its failing to find my Cocoapod dependencies. 

```
import CocoaLumberjack
       ^
Testing failed:
	No such module 'CocoaLumberjack'
** TEST FAILED **
```

**Comment by ksuther** [comment]
Ah, you're using a workspace. How about:

xcodebuild -project YourProject.xcodeproj -scheme YourScheme -workspace YourWorkspace.xcworkspace -showBuildSettings | grep " OBJROOT"

**Comment by janiduw** [comment]
I had to remove -project MyProject.xcodeproj because it was giving the error.
`xcodebuild: error: You cannot specify both an Xcode project and a workspace.`

Executed the following

```
xcodebuild -scheme My_Project -workspace My_Project.xcworkspace -showBuildSettings | grep " OBJROOT"

OBJROOT = /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-fbuvvqycdpxwjtaibtdxnwmvdxqc/Build/Intermediates
```

**Comment by ksuther** [comment]
Thanks, that solves the mystery. Looks like slather needs to know about the workspace you're using in order to find the right location. For now you can probably work around the issue by passing `-b /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-fbuvvqycdpxwjtaibtdxnwmvdxqc/Build/Intermediates` to slather.

**Comment by mindows** [comment]
I'm having the exact same issue today. I'm on Xcode 7.2.1 with slather 2.0.2. My project uses a project file, not a workspace so I followed your suggestion and compared the OBJROOT outputs

Interestingly 
`xcodebuild test ....| grep "OBJROOT" `
and
`xcodebuild --showBuildSettings .... | grep "OBJROOT"

point to totally different locations.. I think `xcodebuild --showBuildSettings`'s output is wrong.

**Comment by ksuther** [comment]
@mindows What about `xcodebuild --showBuildSettings test | grep "OBJROOT"`?

**Comment by janiduw** [comment]
@ksuther Thank you very much. Passing that argument actually worked. However I will wait till this is properly fixed.

**Comment by mindows** [comment]
`xcodebuild --showBuildSettings test | grep "OBJROOT"` points to a directory that's totally different from `xcodebuild test |grep "OBJROOT"`

so, in summary:
`xcodebuild test | grep "OBJROOT"` --> correct output directory
`xcodebuild -showBuildSettings test | grep "OBJROOT"`--> some other output directory 
`xcodebuild -showBuildSettings | grep "OBJROOT"`--> some other output directory (same as above)

**Comment by mindows** [comment]
ah, something interesting. I went to Xcode->Projects and removed my project from the list (not just the derived data directory) and re-ran `xcodebuild test | grep "OBJROOT"`. Now all 3 grep outputs match. At least they are consistent. I'm re-runing my tests to see if the profdata will be picked up by slather correctly.

**Comment by alexcosmin** [comment]
I'm having the same issue as well. Using `slather 2.0.2` and `Xcode 7.3`. I'm using a `xcworkspace` as _janiduw_, due to CocoaPods.
I also tried cleaning the `DerivedData` folder, without any luck. 
My `slather` command:
```
slather coverage --verbose --input-format profdata --cobertura-xml --ignore "../**/*/Xcode*" --output-directory slather-report --scheme "Ad Hoc" MyProjectName.xcodeproj
```
Output:
```Slathering...
/Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:144:in `profdata_coverage_dir': No coverage directory found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:310:in `find_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:288:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:205:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/command/coverage_command.rb:43:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
```

Based on the discussion above, I tried the same as @ksuther suggested.
```
xcodebuild -project MyProjectName.xcodeproj -scheme 'Ad Hoc' -showBuildSettings | grep " OBJROOT"
OBJROOT = /Users/MyUser/Library/Developer/Xcode/DerivedData/MyProjectName-eiyxdnjmcsbvmabukvvfqgwogytf/Build/Intermediates
```

```
xcodebuild -scheme 'Ad Hoc' -workspace MyProjectName.xcworkspace -showBuildSettings | grep " OBJROOT"
OBJROOT = /Users/MyUser/Library/Developer/Xcode/DerivedData/MyProjectName-cccatgpdstnsmbdcrdlwiacwgxon/Build/Intermediates
```
Therefore the paths are different for me as well. Trying adding the path to the `slather` command didn't change anything.
```
slather coverage --verbose --input-format profdata --cobertura-xml --ignore "../**/*/Xcode*" --output-directory slather-report --scheme "Ad Hoc" -b /Users/MyUser/Library/Developer/Xcode/DerivedData/MyProjectName-cccatgpdstnsmbdcrdlwiacwgxon/Build/Intermediates MyProjectName.xcodeproj
```
Still fails with the same error:
```Slathering...
/Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:144:in `profdata_coverage_dir': No coverage directory found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:310:in `find_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:288:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/project.rb:205:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/lib/slather/command/coverage_command.rb:43:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.0.2/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
```

Any other ideas for what to try? :)

**Comment by ksuther** [comment]
@alexcosmin What's the actual path of the CodeCoverage directory that's being created?

**Comment by brennantaylor** [comment]
I am also seeing this with 2.0.2

**Comment by palusik86** [comment]
Same as here, 2.0.2 version, Xcode 7.3

**Comment by ksuther** [comment]
I'm working on a solution, would appreciate some testing when it's done. I don't use workspaces in my own projects so I'm likely missing some edge cases.

**Comment by ksuther** [comment]
This is a work in progress, but it'd be great if someone could try out https://github.com/ksuther/slather/tree/workspace-support with a workspace.

It adds a workspace option to the yaml config file as well as a `--workspace` argument.

Usage is something like:

`bundle exec slather coverage -s --workspace MyWorkspace.xcworkspace --scheme MyScheme --verbose MyProject.xcodeproj`

**Comment by danthorpe** [comment]
Hi - on a similar, but possible unrelated note. I've had similar issues, using @fastlane scan - took me a while to figure out that [by default it builds using a Release configuration](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/options.rb#L107), instead of Debug. And hence when slathering I was getting the same error as the OP.

**Comment by gblotter** [comment]
@ksuther how do you compile the gem from your branch?  I'd love to test out your workspace fix...

**Comment by ksuther** [comment]
@gblotter `gem build slather.gemspec && gem install slather-2.0.1.gem`

If you use bundler and a gemfile, more instructions here: https://github.com/SlatherOrg/slather/issues/173

**Comment by gblotter** [comment]
@ksuther Works like a charm!

**Comment by neonichu** [comment]
@ksuther the branch LGTM :+1:

**Comment by janiduw** [comment]
This worked for me. Thank you so much @ksuther . Any idea when this will be available in rubygems ?

**Comment by alexcosmin** [comment]
Awesome! Worked fine for me as well. Thank you for the quick fix! @janiduw version 2.1.0 is now available.

**Comment by palusik86** [comment]
Stil some problems:

```
/Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:158:in `profdata_coverage_dir': No coverage directory found. (StandardError)
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:363:in `find_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:314:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/project.rb:221:in `configure'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/lib/slather/command/coverage_command.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/slather-2.1.0/bin/slather:15:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<main>'
No coverage directory found.

```

**Comment by satgh12** [comment]
I am using Slather 2.2.1. Xcode is 7.3.1.
Coverage profdata is at:
/Users/USERNAME/Library/Developer/Xcode/DerivedData/Build/Intermediates/CodeCoverage/Coverage.profdata

Binary is at:
/Users/USERNAME/Library/Developer/Xcode/DerivedData/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/MMTests.app/MMTests

I tried -b option as well.  That did not work.


bundle exec slather coverage \
    --input-format profdata \
    --teamcity \
    --ignore "../**/*/Xcode*" \
    --output-directory slather-report \
    --scheme ${SCHEME} \
    -b ${PROFDATA} \
    ${PROJECT}

xcodebuild -project ${PROJECT} -scheme ${SCHEME} -sdk iphonesimulator -configuration Debug -showBuildSettings > ${BUILD_SETTINGS}
PROJECT_TEMP_ROOT=$(grep -m1 PROJECT_TEMP_ROOT ${BUILD_SETTINGS} | cut -d= -f2 | barges)
PROFDATA=$(find ${PROJECT_TEMP_ROOT} -name "Coverage.profdata" | head -n 1)


I still keep getting this error message:
Slathering...
/Library/Ruby/Gems/2.0.0/bundler/gems/slather-36db6044bb5b/lib/slather/project.rb:112:in `profdata_coverage_dir': No coverage directory found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj` (StandardError)
	from /Library/Ruby/Gems/2.0.0/bundler/gems/slather-36db6044bb5b/lib/slather/project.rb:261:in `find_binary_file'
	from /Library/Ruby/Gems/2.0.0/bundler/gems/slather-36db6044bb5b/lib/slather/project.rb:256:in `configure_binary_file'
	from /Library/Ruby/Gems/2.0.0/bundler/gems/slather-36db6044bb5b/lib/slather/project.rb:179:in `configure'
	from /Library/Ruby/Gems/2.0.0/bundler/gems/slather-36db6044bb5b/bin/slather:48:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/clamp-0.6.5/lib/clamp.rb:6:in `Clamp'
	from /Library/Ruby/Gems/2.0.0/bundler/gems/slather-36db6044bb5b/bin/slather:6:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/bin/slather:22:in `load'
	from /Library/Ruby/Gems/2.0.0/bin/slather:22:in `<main>'

**Comment by mike011** [comment]
Any update?

**Comment by jpecknerhelix** [comment]
In case anyone's having this same issue when trying to run Slather in their test post-actions, it appears that Xcode doesn't generate the Coverage.profdata file until after the post-actions complete. As a workaround, set your post-action script to execute as a background process, with a short sleep at the beginning so the file has time to be written out:

    # Redirect output to stderr, since stdout isn't available during the post-action phase
    exec > ${PROJECT_DIR}/MyTests-Slather.log 2>&1

    # Running Slather in a sleep-delayed background block is necessary for the Coverage.profdata file to be generated before Slather actually runs
    {
        sleep 2
        slather coverage -s --verbose --scheme MyScheme --workspace ${PROJECT_DIR}/../MyWorkspace.xcworkspace ${PROJECT_DIR}/MyProject.xcodeproj
    }&

**Comment by sercan5534** [comment]
Hey @jpecknerhelix,
I've had same issue and solved with your workaround. Thanks

**Comment by showpony** [comment]
I am still seeing this issue when I try and execute slather (2.4.2) after generating code coverage using Xcode 9 beta 2.   

`slather coverage --verbose --scheme "my scheme" --html --workspace MyWorkspace.xcworkspace`

And getting the following error:

`Slathering...
`<PBXSourcesBuildPhase UUID=`1D60588E0D05DD3D006BFB54`>` attempted to initialize an object with an unknown UUID. `A7763F9A1D234B6F006DEA52` for attribute: `files`. This can be the result of a merge and  the unknown UUID is being discarded.
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
	If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)

/Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/project.rb:171:in `profdata_coverage_dir': No coverage directory found. (StandardError)
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/project.rb:409:in `block in find_binary_files'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/project.rb:408:in `each'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/project.rb:408:in `find_binary_files'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/project.rb:350:in `configure_binary_file'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/project.rb:236:in `configure'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/lib/slather/command/coverage_command.rb:53:in `execute'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/matt/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/slather-2.4.2/bin/slather:17:in `<top (required)>'
	from /Users/matt/.rbenv/versions/2.3.1/bin/slather:22:in `load'
	from /Users/matt/.rbenv/versions/2.3.1/bin/slather:22:in `<main>'
`

**Comment by janeshsutharios** [comment]
> Thanks, that solves the mystery. Looks like slather needs to know about the workspace you're using in order to find the right location. For now you can probably work around the issue by passing `-b /Users/janidu.wanigasuriya/Library/Developer/Xcode/DerivedData/My_Project-fbuvvqycdpxwjtaibtdxnwmvdxqc/Build/Intermediates` to slather.

How can i pass `-b` can you please tell ?  following is Directory - 

`$xcodebuild -project fb.xcodeproj -scheme fb -configuration Debug -showBuildSettings | grep " OBJROOT"
    OBJROOT = /Users/janeshsuthar/Library/Developer/Xcode/DerivedData/fb-cgdurckckznxhaeuopizzbsvgfgo/Build/Intermediates.noindex`

Please tell how can i proceed further i am also having same issue. ?@ksuther
