### ISSUE TITLE
Unable to find coverage data for Framework

### ISSUE THREAD

**Issue by AidenMontgomery** [SlatherOrg/slather#176]
I am trying to get coverage data from a framework that I am writing.
In xcode I can see the coverage results after running tests, so I believe that I have the right settings for generating the coverage data.

I have a slather file that specifies the following: -

```ruby
coverage_service: cobertura_xml
input_format: profdata
output_directory: output_folder
xcodeproj: <project location>
scheme: <test scheme>
```

When I run `slather coverage` I see the following error: -

```
/Library/Ruby/Gems/2.0.0/gems/slather-2.0.1/lib/slather/project.rb:127:in `profdata_coverage_dir': No coverage directory found. Are you sure your project is setup for generating coverage files? Try `slather setup your/project.xcodeproj`
```

I have looked at the location of the error and I think that my issue is to do with how Slather is detecting the coverage data folder, or how I have things configured when running my tests.

project.rb line 120

```ruby
dir = Dir[File.join("#{build_directory}","/**/CodeCoverage/#{self.scheme}")].first
```

This appears to be looking for the code coverage data in a folder which has the name of the Scheme used to build the project.

Looking in the derived data folder for the project I see the following structure.

```
build/Intermediates/CodeCoverage/
     ↳ Coverage.profdata
     ↳ Intermediates/
     ↳ Products/
     ↳ ProfileData/
            ↳ -14542.profdata
```

As there doesn't seem to be a folder created with the scheme name I updated the line in Slather to be: -

```ruby
dir = Dir[File.join("#{build_directory}","/**/CodeCoverage/")].first
```

Running Slather again appears to be generating code coverage data.

I am using Xcode 7.3 and running my tests on the command line using Scan from FastLane, which is using xcodebuild to execute the tests.

Does it look like I am doing something wrong?

**Comment by ksuther** [comment]
It looks like you're hacking on slather 2.0.1, can you try 2.0.2?

**Comment by AidenMontgomery** [comment]
Of course, I will give that a go.

**Comment by AidenMontgomery** [comment]
Thanks, that fixed the issue that I was having.
