### ISSUE TITLE
Teamcity support removed?

### ISSUE THREAD

**Issue by themackworth** [SlatherOrg/slather#177]
After updating my gem file from pointing at the commit on master that added teamcity support to 2.0.2, I got the following error `ERROR: Unrecognised option '--teamcity'`

It looks like d4bf4b4d3baccc41cdfdce6f7c7dd3c49f4b3e25 removed teamcity support when restructuring the files?

**Comment by neonichu** [comment]
Sorry for this, overlooked it when merging that commit and there aren't really tests for each of the individual CI flags (the underlying code still existed).
