### ISSUE TITLE
Update fastlane slather action to recieve new parameters

### ISSUE THREAD

**Issue by kdawgwilk** [SlatherOrg/slather#181]
I will take a crack at this but just want to have a record of it here.

- [ ] TeamCity
- [x] Workspace

These are the two I need most but if there are any others let me know 😊

**Comment by yakimant** [comment]
I agree, but guess, that it should go to fastlane project:
https://github.com/fastlane/fastlane/issues

**Comment by ksuther** [comment]
There's a PR for workspace at fastlane:

https://github.com/fastlane/fastlane/pull/4109
https://github.com/fastlane/fastlane/issues/4165

**Comment by ksuther** [comment]
fastlane 1.82.0 includes a workspace option for slather.

**Comment by sbhklr** [comment]
@kdawgwilk @ksuther Can we close this issue?

**Comment by ksuther** [comment]
Closing it because the most common request was for the workspace parameter. If TeamCity is still needed then that should be done in fastlane, not here.
