### ISSUE TITLE
Is TeamCity support implemented?

### ISSUE THREAD

**Issue by thalmicMark** [SlatherOrg/slather#184]
I see in the docs there's a `--teamcity` option, but when I run ...

    slather coverage --teamcity -s --scheme <MY_SCHEME>

... I get ...

    ERROR: Unrecognised option '--teamcity'

    See: 'slather coverage --help'

Should the README be updated?

**Comment by ksuther** [comment]
Have you updated to 2.1.0?

**Comment by thalmicMark** [comment]
Ah, I was on an older version. Thanks!
