### ISSUE TITLE
Multiple test targets in single scheme, not all coverage included

### ISSUE THREAD

**Issue by thalmicMark** [SlatherOrg/slather#186]
I've got a project that contains an app (which has tests), and a separate framework target (which has its own tests). I modified the app's default scheme to also run my framework's test target when executing a test command, and enabled code coverage.

When I test in Xcode, both test targets are run, and I see results and coverage data for both. When I run slather on our build machine however, it seems to only get coverage data for my app's test target (and not my framework's test target).

Is this a limitation of slather, or do I need to organize my tests differently? I realize I could individually test my app's and framework's schemes, and then run slather for both schemes, but I'm going to be adding a lot more frameworks, and I don't want to have to update my build machine every time I add another framework target.

**Comment by ksuther** [comment]
I think you're running into the same thing as #157.

Having slather automatically check all the relevant binaries would definitely be nice to have.

**Comment by thalmicMark** [comment]
Ah you're right. I'll close this issue.
