### ISSUE TITLE
Add a `--version` flag

### ISSUE THREAD

**Issue by jschneier** [SlatherOrg/slather#187]
A way to quickly check which version of a command line tool I am using exists in every single one I use aside from slather. I'd be happy to add it if necessary.
```
slather --version
slather 2.1.0
```

**Comment by neonichu** [comment]
Definitely, I was missing it myself the other day :)

**Comment by bootstraponline** [comment]
`slather version` works now #208, which should resolve this issue.

**Comment by jschneier** [comment]
Thanks!
