### ISSUE TITLE
Cannot load such file -- xcodeproj (LoadError)

### ISSUE THREAD

**Issue by giacgbj** [SlatherOrg/slather#204]
ijhack:projectName jhack$ slather coverage --ignore ../* --input-format profdata -i .*Tests.* --cobertura-xml --output-directory sonar-reports --workspace projectName.xcworkspace --scheme projectName projectName.xcodeproj
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- xcodeproj (LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.1.0/lib/slather/project.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.1.0/lib/slather.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.1.0/bin/slather:4:in `require_relative'
	from /usr/local/lib/ruby/gems/2.3.0/gems/slather-2.1.0/bin/slather:4:in `<top (required)>'
	from /usr/local/bin/slather:22:in `load'
	from /usr/local/bin/slather:22:in `<main>'

Same error if I just run "slather" without any argument.

Please let me know if you need more information.

**Comment by ksuther** [comment]
Do you have the xcodeproj gem installed?
