### ISSUE TITLE
Improve API for multi-project coverage

### ISSUE THREAD

**Issue by bootstraponline** [SlatherOrg/slather#210]
https://github.com/SlatherOrg/slather/issues/96#issuecomment-218555169 is what I'm currently using. Specifically the private method & instance_variable_get aren't great.

I'd like to update project.rb with the following:

- [x] Make `coverage_files` a public method
- [x] Define an accessor for `@docs`

If there are no issues, then I'll submit a PR.

**Comment by neonichu** [comment]
Sounds good to me :+1:
