### ISSUE TITLE
Slathering takes longer than 10 minutes

### ISSUE THREAD

**Issue by pietbrauer** [SlatherOrg/slather#212]
I updated slather to 2.2.0 and it ran perfectly a few times but I get occasional timeouts on CircleCI because `slather coverage` just hangs:

```bash
bundle exec slather coverage
Slathering...

command make ci_test took more than 10 minutes since last output
```

I just open this issue in case someone has a solution. I currently don't have time to investigate.

**Comment by ksuther** [comment]
Maybe take a look at #197?

**Comment by pietbrauer** [comment]
Yep. Thanks!
