### ISSUE TITLE
warning: X functions have mismatched data.

### ISSUE THREAD

**Issue by beloso** [SlatherOrg/slather#215]
I am getting this warning

I would like to know what it means and how can I fix it?

**Comment by sbhklr** [comment]
@TiagoVeloso It most likely means that the coverage data wasn't generated for the binary file you are processing the coverage file against.

> The number of functions that couldn't have their profiles mapped.

> 
> This is a count of functions whose profile is out of date or otherwise can't be associated with any coverage information.
> 
> Definition at line 438 of file CoverageMapping.h.

**Comment by hons82** [comment]
I got this now with Xcode 8.
However the files at the end seem to be processed correctly

**Comment by santhoshs5** [comment]
I am getting this warning and many of the files code coverage is not begin generated.

Can i know the reason , I have a different folder structure for my code base. I am using Xcode 7.3.1

Is that the reason?

**Comment by cs-kaique-pantosi** [comment]
I am facing the same problem as @santhoshs5 and I am using Xcode 7.3.1 to. Could this be a problem of a wrong merge?

**Comment by AnthonyUccello** [comment]
I can confirm at least 1 case where @sbhklr is correct.

I had this error and when I checked my Xcode scheme, somehow the coverage flag was no longer toggled. Even though I had run it before (and slather had made reports) it seems the binary for the test file was missing.

So make sure that:
-Your scheme has the coverage data flag set
-You have run a successful unit test for your project
