### ISSUE TITLE
Bundle install fails due to nokogiri 1.6.8 problem

### ISSUE THREAD

**Issue by mikelupo** [SlatherOrg/slather#227]
Yosemite 10.10.5
This was working, and now suddenly it has stopped.
The command and it's subsequent output as well as mkmf.log snippet is included below.

I notice that some of my Jenkins Mac Mini slaves when running the bundle install command install nokogiri 1.6.7.2, this one which is experiencing the failure is trying to install nokogiri 1.6.8.
What makes this difference?
============= bundle install ==============
bundle install
Fetching gem metadata from https://rubygems.org/...............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.9.0
Using thread_safe 0.3.5
Using claide 1.0.0
Using clamp 0.6.5
Using colored 1.2
Using mini_portile2 2.1.0
Using pkg-config 1.1.7
Using bundler 1.11.2
Using tzinfo 1.2.2
Installing nokogiri 1.6.8 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb --use-system-libraries
Using pkg-config version 1.1.7
checking if the C compiler accepts ... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using system libraries.
checking for libxml-2.0... no
checking for libxslt... no
checking for libexslt... no
ERROR: cannot discover where libxml2 is located on your system. please make sure `pkg-config` is installed.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
	--help
	--clean
	--use-system-libraries
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-libxml-2.0-config
	--without-libxml-2.0-config
	--with-pkg-config
	--without-pkg-config
	--with-pkg-config
	--without-pkg-config
	--with-override-variables
	--without-override-variables
	--with-xslt-dir
	--without-xslt-dir
	--with-xslt-include
	--without-xslt-include=${xslt-dir}/include
	--with-xslt-lib
	--without-xslt-lib=${xslt-dir}/lib
	--with-libxslt-config
	--without-libxslt-config
	--with-pkg-config
	--without-pkg-config
	--with-exslt-dir
	--without-exslt-dir
	--with-exslt-include
	--without-exslt-include=${exslt-dir}/include
	--with-exslt-lib
	--without-exslt-lib=${exslt-dir}/lib
	--with-libexslt-config
	--without-libexslt-config
	--with-pkg-config
	--without-pkg-config

Gem files will remain installed in /var/folders/8r/84r5yjgs6g79sncp7rjqflnr0000gq/T/bundler20160609-42888-n8l47cnokogiri-1.6.8/gems/nokogiri-1.6.8 for inspection.
Results logged to /var/folders/8r/84r5yjgs6g79sncp7rjqflnr0000gq/T/bundler20160609-42888-n8l47cnokogiri-1.6.8/gems/nokogiri-1.6.8/ext/nokogiri/gem_make.out
Using activesupport 4.2.6
An error occurred while installing nokogiri (1.6.8), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.

=============== SNIP mkmf.log ==============
"xcrun clang -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14 -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_SYNC_BUILTINS  -Wno-error=unused-command-line-argument-hard-error-in-future  -arch x86_64 -arch i386  -c conftest.c"
warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Werror=unused-command-line-argument-hard-error-in-future'; did you mean '-Werror=unused-command-line-argument'? [-Wunknown-warning-option]
1 warning generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() {return 0;}
/* end */

package configuration for libxslt is not found
have_package: checking for libxslt... -------------------- no

DL is deprecated, please use Fiddle
--------------------

package configuration for libexslt is not found
have_package: checking for libexslt... -------------------- no

--------------------

"xcrun clang -E -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin14 -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/backward -I/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0 -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2/ -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_SYNC_BUILTINS   conftest.c -o conftest.i"
conftest.c:3:10: fatal error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <libxml/xmlversion.h>
/* end */

**Comment by neonichu** [comment]
`bundle install` will pick the newest available version satisfying a requirement, unless you specify concrete versions or upper bounds in the `Gemfile`. 

You can check out <http://buegling.com/blog/2015/4/26/building-nokogiri-on-os-x> for some nokogiri installation troubleshooting advice.

**Comment by mikelupo** [comment]
Thank you @neonichu! That was helpful.

**Comment by brendangillies** [comment]
How did you solve this?? Struggling with the same issue but am not able to find the answer here...

**Comment by mikelupo** [comment]
@brendangillies I think what I had to do was to force the install of Nokogiri 1.6.7.2 first.
Then I was able to install the slather gem. 




-----Original Message-----

**Comment by myseven** [comment]
maybe you need to update your ruby

**Comment by ts-silvio** [comment]
In OSX this worked for me:

```
xcode-select --install
gem install nokogiri
```

from here: http://stackoverflow.com/a/34653921

**Comment by ptibbetts** [comment]
I've just updated to MacOS Sierra and had this issue, installing the command line tools as mentioned above by @ts-silvio worked for me

**Comment by SteveOscar** [comment]
As @ptibbetts said, I've just updated to Sierra, trying to start a Rails 5 project, @ts-silvio 's answer got me past the Nokogiri error.

**Comment by sleekweasel** [comment]
I tried xcode-select to choose 7.3.1 instead of xcode-8, but bundle install still failed with the same error.

What worked for me was (with 7.3.1 still selected, 8.0 might have worked) 'brew install libxml2' and then 'gem install nokogiri -v 1.6.8.rc3'. Brew warned about libxml2 already being provided, and said it wasn't going to link it into /usr/local because it was 'keg-only'.

We don't want to upgrade this system to Sierra yet in case Apple's broken yet another part of our set-up.

**Comment by jayleicn** [comment]
For Sierra,  the following code solved my problem (ERROR: Failed to build gem native extension.)
```
brew unlink gcc-4.2      # you might not need this step
gem uninstall nokogiri
xcode-select --install
gem install nokogiri
 ```

Reference,  http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x

**Comment by cmavromoustakos** [comment]
This fixes it for me:

    gem install nokogiri -- --use-system-libraries=true --with-xml2-include=/usr/include/libxml2

**Comment by Lax** [comment]
```
xcode-select --install
```
works for me.

This may happen after I reinstalled Xcode.

**Comment by bryanwongbh** [comment]
@ts-silvio 's solution worked for me; managed to  install nokogiri and proceed with rails 5 installation

**Comment by dlamichhane** [comment]
`xcode-select --install` works for me. I was unable to build the gem after updating to macOS Sierra

**Comment by elimcjah** [comment]
@ts-silvio has the answer that worked for me:
```
xcode-select --install
gem install nokogiri
```

**Comment by bobzhen** [comment]
I just uninstall all versions of nokogiri, and reinstall it by following official installation tutorial.
```
http://www.nokogiri.org/tutorials/installing_nokogiri.html#mac_os_x
```

**Comment by timlauter** [comment]
As others have mentioned, it resolved my update to Sierra.

**Comment by netuoso** [comment]
`xcode-select --install; bundle install` worked for me despite already having command line tools. I suggest to try this first if you are having issues.

**Comment by Kcnarf** [comment]
@ts-silvio's solution `xcode-select --install ; bundle install` didn't work, telling me to install pkg-config.

So I `brew install pkg-config`, but got `Error: The 'brew link' step did not complete successfully`.
So I `brew link --overwrite pkg-config`
And then `bundle install` works fine

**Comment by jerryzhoujw** [comment]
Follow @cmavromoustakos 's solution. I use `gem install slather -- --use-system-libraries=true --with-xml2-include=/usr/include/libxml2`

**Comment by Rifinio** [comment]
I couldn't install slather on OS Sierra, and i tried almost everything with no success.
**ts-silvio** is my hero, his solution works great 👍

**Comment by DaveCollinsJr** [comment]
And more than a year later @ts-silvio 's commands worked after an Apple Xcode update.  Also make sure you have run Xcode _at least once_ to accept the new terms and conditions.  

> I am altering the deal... Pray I don't alter it any further.

**Comment by ihouse10** [comment]
Doing `bundle update` fixes this problem for me.

**Comment by fabb** [comment]
I use a `bundler` and a `Gemfile` for installing `slather` (and `fastlane`). I still have the problem of the OP on macOS High Sierra. I do not want to install `nokogiri` globally, because I use `bundler` and only install the gems into a local `vendor/bundle` folder.
Any ideas how to fix the issue properly when using `bundler`?

**Comment by fabb** [comment]
Ok I found it out: I had set `BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"` in `~/.bundle/config` which caused problems. I removed the setting via `bundle config --delete build.nokogiri`. Now my Gemfile containing slather installs without any further workarounds! 🎉

**Comment by nitrnitr** [comment]
with newer versions of `brew` this is something like `gem install nokogiri -- --with-xml2-include=/usr/local/opt/libxml2/`

do a reinstall of libxml2 with brew and it will tell you where it is located, then use that path. without the `--use-system-libraries=true`!

**Comment by jaredh159** [comment]
tried what @fabb mentioned about deleting `BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"` in `.bundle/config` and it fixed the problem for me.

**Comment by rohandaxini** [comment]
For one of my old Rails 4 application, I wanted to install `nokogiri -v 1.6.8.1` and earlier locked version was `1.6.0`. When I started installing nokigiri gem, I was bitten by this same issue.

On my latest macOS `Mojave 10.14.4`, following option of `xcode-select` did not work for me.
```
xcode-select --install
```
It's giving error as `xcode-select: error: command line tools are already installed, use "Software Update" to install updates` and when I check then all softwares are up-to date.

As suggested by @nitrnitr , this solution worked for me finally
```
gem install nokogiri -v 1.6.8.1 -- --with-xml2-include=/usr/local/opt/libxml2/
```
