### ISSUE TITLE
Non-ASCII file names

### ISSUE THREAD

**Issue by giacgbj** [SlatherOrg/slather#230]
It seems that non-ASCII filenames are not properly handled. 
The name of the file is "Modalità.swift".

$ slather coverage --jenkins --cobertura-xml --build-directory reports/DerivedData --output-directory reports --scheme scheme --workspace projectName.xcworkspace --binary-basename projectName.xcodeproj
Slathering...
/Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_info.rb:74:in `realpath': No such file or directory @ realpath_rec - /Users/jhack/a/valid/path/to/Modalita��.swift (Errno::ENOENT)
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_info.rb:74:in`realpath'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_info.rb:74:in `source_file_pathname_relative_to_repo_root'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_service/cobertura_xml_output.rb:35:in`block in grouped_coverage_files'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_service/cobertura_xml_output.rb:33:in `each'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_service/cobertura_xml_output.rb:33:in`grouped_coverage_files'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_service/cobertura_xml_output.rb:59:in `create_xml_report'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/coverage_service/cobertura_xml_output.rb:18:in`post'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/command/coverage_command.rb:88:in `post'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/lib/slather/command/coverage_command.rb:52:in`execute'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in`execute'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in`run'
    from /Users/jhack/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/slather-2.2.1/bin/slather:17:in `<top (required)>'
    from /Users/jhack/.rbenv/versions/2.3.0/bin/slather:22:in`load'
    from /Users/jhack/.rbenv/versions/2.3.0/bin/slather:22:in `<main>'

**Comment by ksuther** [comment]
This should work in master now (#259).
