### ISSUE TITLE
No output has been received in the last 10m0s

### ISSUE THREAD

**Issue by eikebartels** [SlatherOrg/slather#234]
Hey, 

I'm trying to use Slather and Coveralls together. On Travis I get 

No output has been received in the last 10m0s

Any idea how to solve this?

**Comment by neonichu** [comment]
That's probably just `xcodebuild` hanging, did you try to rerunning the build? Is it consistently reproducible?

**Comment by eikebartels** [comment]
ok after struggling around if finally solved it. Seems to been my issue. Thanks

**Comment by eikebartels** [comment]
So I run into this issue again. Half of the time it is passing, another half it is failing

**Comment by ksuther** [comment]
This sounds similar to #197. You can try specifying the build directory explicitly, or add the xcodebuild flags described in http://www.openradar.me/radar?id=5549442786656256 to see if that avoids the hang.

**Comment by eikebartels** [comment]
I switch to the fastlane action for slather and now I don't have any issues at all anymore. 

Here my line. Maybe it will help someone else 
```
lane :test_ci do

    scan(
      workspace: WORKSPACE,
      device: "iphonesimulator",
      scheme: SCHEME,
      clean: false,
      code_coverage: true,
    )

    slather(
      coveralls:true,
      workspace: WORKSPACE,
      proj: PROJECT, 
      scheme: SCHEME,
      simple_output:true,
      ignore: ["../*", "Pods/*"],
      source_directory: "Project/",
      verbose: true,
    )
    
  end
```
