### ISSUE TITLE
pod install crash after switching to Slather 2.3

### ISSUE THREAD

**Issue by nikolaykasyanov** [SlatherOrg/slather#237]
I migrated to 2.3 recently because of https://github.com/SlatherOrg/slather/issues/235, and now I'm getting an error during `pod install`:

```
Errno::ENOENT - No such file or directory - /Users/MaxMustermann/src/whatever/Pods/Pods.xcodeproj/xcshareddata/xcschemes/Pods.xcscheme
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/scheme.rb:33:in `initialize'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/scheme.rb:33:in `new'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/xcodeproj-1.1.0/lib/xcodeproj/scheme.rb:33:in `initialize'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:36:in `new'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:36:in `block in slather_setup_for_coverage'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:34:in `each'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.3.0/lib/slather/project.rb:34:in `slather_setup_for_coverage'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/slather-2.3.0/lib/cocoapods_plugin.rb:7:in `block in <top (required)>'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/hooks_manager.rb:111:in `call'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:473:in `run_plugins_post_install_hooks'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:454:in `perform_post_install_actions'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:121:in `install!'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/bin/pod:23:in `load'
/Users/MaxMustermann/.rbenv/versions/2.0.0-p481/bin/pod:23:in `<top (required)>'
```

Am I missing something? I tried "Autocreate Shemes Now", but no luck.

**Comment by nikolaykasyanov** [comment]
I just realized that I was able to do `pod install` successfully at least once after upgrade, though.

**Comment by neonichu** [comment]
Not sure, I'd try to delete `/Users/MaxMustermann/src/whatever/Pods/Pods.xcodeproj/xcshareddata` and see what happens.

**Comment by nikolaykasyanov** [comment]
@neonichu actually it's gitignored in my project and empty.

I'm not sure why does ` Xcodeproj::Project.schemes(self.path)` returns `["Pods"]`, there's no target "Pods" anywhere.

**Comment by neonichu** [comment]
Can you look for `xcschememanagement.plist` inside the `Pods.xcodeproj` bundle and see if it is referenced in there?

**Comment by nikolaykasyanov** [comment]
@neonichu nope. Gonna play with xcodeproj in irb to figure out what's going wrong here.

**Comment by nikolaykasyanov** [comment]
@neonichu 

I found the reason: https://github.com/CocoaPods/Xcodeproj/blob/1-2-stable/lib/xcodeproj/project.rb#L767

If project has no shared schemes, it returns the name of the project. Blame didn't help me to find any rationale behind that, though.

**Comment by nikolaykasyanov** [comment]
I suppose scheme can be skipped if its file doesn't exist.

But I wonder why does slather do [this](https://github.com/SlatherOrg/slather/blob/master/lib/slather/project.rb#L30-L43) for Pods.xcodeproj? It's not like it's possible to have test targets here.

**Comment by neonichu** [comment]
What's the configuration you're using for slather?

**Comment by nikolaykasyanov** [comment]
@neonichu 

```
source_directory: .
xcodeproj: AppName.xcodeproj

ignore:
  - Pods/*
  - ../*
```

**Comment by nikolaykasyanov** [comment]
As I can see from CocoaPods plugin, it just applies `slather_setup_for_coverage` to Pods project and that's it, no configuration involved: https://github.com/SlatherOrg/slather/blob/6b9e8eeff90f314c67bf9c4cf9ac88c9ff227545/lib/cocoapods_plugin.rb

**Comment by neonichu** [comment]
Oh, I missed that you're using the CP plugin — haven't personally used that in a while.

**Comment by nikolaykasyanov** [comment]
@neonichu yeah, I have some parts of the app as development pods, so I have to use it.

**Comment by nikolaykasyanov** [comment]
@neonichu how about disabling scheme modification code completely inside the plugin? I'm halfway there, can make a PR.

**Comment by neonichu** [comment]
TBH, I'm not sure about the usefulness of the plugin in general anymore — there used to be the point  that it set up the flags for code coverage, but since Xcode 7, those aren't actually used anymore.

**Comment by nikolaykasyanov** [comment]
@neonichu I remember not getting coverage of my development pods without `CLANG_ENABLE_CODE_COVERAGE` set in corresponding targets.

I'll check if that's still the case.

**Comment by nikolaykasyanov** [comment]
@neonichu you're right, one don't need this plugin anymore.
