### ISSUE TITLE
Slather not generating any UI test reports

### ISSUE THREAD

**Issue by devikirankhode** [SlatherOrg/slather#241]
I'm working on Xcode project(swift language).I'm using slather to convert coverage.profdata to cobertura.xml.It's just generating reports for unit test results.but not the UI test results.
Please help me out.

`slather coverage --html --scheme "Myscheme"  --output-directory "coverage/reports" --workspace abc.xcworkspace --input-format profdata --build-directory "/Users/xxxx/Library/Developer/Xcode/DerivedData" --source-directory . abc.xcodeproj
`

**Comment by ksuther** [comment]
This is a problem upstream with how coverage is generated. I'd suggest filing a bug with Apple.
