### ISSUE TITLE
Unable to Slather With Large File List

### ISSUE THREAD

**Issue by brianmichel** [SlatherOrg/slather#243]
I'm attempting to run Slather on our repository, however we rely on a series of development pods through CocoaPods to make code available to our main application, share extension, and today widget.

This means that there are thousands of files trying to pass through Slather, and I was recently greeted with this message...

```
Errno::E2BIG: Argument list too long
```

Is this coming from Slather, or llvm-cov? And is there any way to resolve this without making a bunch of coverage reports per folder?

**Comment by neonichu** [comment]
Is that all you're getting as error or is there some larger stacktrace?

**Comment by brianmichel** [comment]
Hey @neonichu here's the full output, I've redacted the gigantic list of source files, and was using Slather 2.3.0:

```
bundle exec slather coverage --jenkins --html --source-files "**/*.{h,m}" --output-directory ~/Desktop/coverage --scheme Orangina --workspace Orangina.xcworkspace Orangina.xcodeproj
```

and got this output...

```
Slathering...
bundler: failed to load command: slather (/Users/brian/.rbenv/versions/2.1.2/bin/slather)
Errno::E2BIG: Argument list too long - xcrun llvm-cov show -instr-profile /Users/brian/Library/Developer/Xcode/DerivedData/Orangina-fmftheyzbzzlhqadndocqxvucxow/Build/Intermediates/CodeCoverage/Coverage.profdata /Users/brian/Library/Developer/Xcode/DerivedData/Orangina-fmftheyzbzzlhqadndocqxvucxow/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/Orangina.app/Orangina
... HUGE FILE LIST WAS HERE ...
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:206:in ``'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:206:in `unsafe_profdata_llvm_cov_output'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:211:in `profdata_llvm_cov_output'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:132:in `block in profdata_coverage_files'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:131:in `each'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:131:in `profdata_coverage_files'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/project.rb:105:in `coverage_files'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/coverage_service/html_output.rb:26:in `post'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:91:in `post'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:53:in `execute'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
/Users/brian/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
/Users/brian/.rbenv/versions/2.1.2/bin/slather:23:in `load'
/Users/brian/.rbenv/versions/2.1.2/bin/slather:23:in `<top (required)>'
```

**Comment by neonichu** [comment]
Don't see an easy way to resolve this. It should be possible to limit the list of files, do multiple `llvm-cov` runs and merge the results in slather.

**Comment by brianmichel** [comment]
> Don't see an easy way to resolve this. It should be possible to limit the list of files, do multiple llvm-cov runs and merge the results in slather.

Do you happen to know where the limits are documented for `llvm-cov` so I can start chunking files as needed?

**Comment by neonichu** [comment]
I think this is hitting the system-wide argument limits, which should be

```bash
$ getconf ARG_MAX
262144
```

This should be the maximum number of bytes for length of argument lists.

**Comment by brianmichel** [comment]
Ahh okay that makes a bit more sense. Thanks!

**Comment by weibel** [comment]
There really is no easy way to solve it. It's the SOURCES in the call to ```llvm-cov show``` which breaks the maximum size for the argument list resulting in an OS level ```E2BIG``` error. 

As I have seen the same error I have been thinking about a few approaches to solving it.

1. The SOURCES argument to ```llvm-cov show``` is optional, so maybe we can avoid it altogether.
2. It might be possible to break up the SOURCES list by splitting the work between multiple invocations of ```llvm-cov show```  which should then be recombined afterwards.
3. Break up my humongous project into smaller chunks and run code coverage on each independently

Link to llvm docs 
http://llvm.org/docs/CommandGuide/llvm-cov.html#llvm-cov-show

**Comment by weibel** [comment]
@diaojunxian  Here's an experimental fork. No guarantees for anything but it looks like it's working https://github.com/weibel/slather
