### ISSUE TITLE
Slather failing with scan 0.11.0

### ISSUE THREAD

**Issue by cbalea** [SlatherOrg/slather#244]
I've described my problem on the `scan` repository as well, but maybe this is something that has to be fixed on the `slather` side.

https://github.com/fastlane/fastlane/pull/5563#issuecomment-239146963

**Comment by KrauseFx** [comment]
I pushed a fix, could you try it and see if that fixes the issue for you? 👍

**Comment by cbalea** [comment]
@KrauseFx version 0.11.3 is working ok. Thanks!

**Comment by KrauseFx** [comment]
Oh yeah, thanks for letting me know 👍
