### ISSUE TITLE
Unable to "ignore" folders.

### ISSUE THREAD

**Issue by arunaousula9421** [SlatherOrg/slather#247]
Hi All,

I did try all possible combinations but couldn't able to  get through this issue. I am trying to ignore few folders for coverage report, it seems not working.

My .slather.yml file

```
coverage_service: cobertura_xml
xcodeproj: abc/abc.xcodeproj
scheme: scheme_name
output_directory: slather-report
workspace: abc.xcworkspace
ignore:
- "*/Pods/*"
- "../**/*/abc*"
```

**Comment by bogdanbolchis** [comment]
It's working for me without any quotes:

```
ignore:
  - ../../../../../Applications/Xcode.app/*
  - Pods/*
```

However, I have another problem with absolute paths, as you can see above.
