### ISSUE TITLE
Slather Cobertura report  integration  with Sonarqube  4.5.7

### ISSUE THREAD

**Issue by Adityachowhan** [SlatherOrg/slather#258]
Has any one  integrated the cobertura.xml  file with the sonarqube  4.5.7

Using Slather 2.3.0
Using Xcode 7+

while running the  generated cobertura.xml against sonar the below error is generated 

 ERROR: Caused by: Error at line 3 of coverage report path to file /slather-report/cobertura.xml
 ERROR: Caused by: Unknown coverage version: Slather 2.3.0. This parser only handles version 1.

The first 3 lines in the file that is generated
<?xml version="1.0"?>
<!DOCTYPE coverage SYSTEM "http://cobertura.sourceforge.net/xml/coverage-04.dtd">
<coverage line-rate="0.0995231183910429" branch-rate="1.0000000000000000" lines-covered="960" lines-valid="9646" branches-covered="0" branches-valid="0" complexity="0.0" timestamp="1476702379" version="Slather 2.3.0">

Thanks in advance

**Comment by ivanalvarado** [comment]
Did you find a solution for this?

**Comment by sax777** [comment]
I also have this problem with Community EditionVersion 7.9.1. Anyone found a fix for this?

**Comment by biolinh** [comment]
I also get too,

> Look at SonarQube documentation to know the expected XML format.
> Caused by: java.lang.IllegalStateException: Unknown report version: Slather 2.4.7. This parser only handles version 1.
