### ISSUE TITLE
Slathering. warning: 3 functions have mismatched data.

### ISSUE THREAD

**Issue by ravikanthv** [SlatherOrg/slather#260]
Hello Slather Team

I'm running into an issue while running slather, it throws "Slathering. warning: 3 functions have mismatched data."How do I check which 3 function are causing mismatch and how to fix this issue.

Appreciate your help

**Comment by ksuther** [comment]
This is a warning from llvm-cov, not slather. You may have more luck figuring out where the warnings are coming from if you run llvm-cov manually (e.g. `llvm-cov show -instr-profile /path/to/Coverage.profdata /path/to/MyApp.app/MyApp`)
