### ISSUE TITLE
Slather needs to have explicit input format set with Xcode 8.1 on travis

### ISSUE THREAD

**Issue by GeroHerkenrath** [SlatherOrg/slather#262]
I'm just opening this issue to inform, I did manage to work around it already.
I'm unsure whether this affects people with different setups as well, but I came across an error when running my build on travis:

    $ slather coverage -c -s -t --ignore '../*' -b ${TRAVIS_BUILD_DIR}/myDerivedData --verbose
    Slathering...
    /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/slather-2.2.1/lib/slather/project.rb:289:in `input_format=': undefined method `<' for     nil:NilClass (NoMethodError)
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/slather-2.2.1/lib/slather/command/coverage_command.rb:122:in `setup_input_format'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/slather-2.2.1/lib/slather/command/coverage_command.rb:42:in `execute'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/slather-2.2.1/bin/slather:17:in `<top (required)>'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/slather:23:in `load'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/slather:23:in `<main>'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
        from /Users/travis/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `<main>'

As this shows it looks like the `input_format` is not determined correctly. Adding `--input-format profdata` to the slather command solves the issue for me. As you see I might have an uncommon setup of the parameters, here's the .slather.yml file to complete the description:

    coverage_service: coveralls
    xcodeproj: Example/Trustbadge.xcodeproj
    scheme: Trustbadge_Example
    workspace: Example/Trustbadge.xcworkspace
    source_directory: Pod/Classes
    binary_basename: Trustbadge

I use a specific, custom directory for derived data to have slather find the coverage files, this was a workaround for it not finding them on travis (this seems specific to a cocoapod setup like mine and is fine).

My guess is that, at least under my conditions, slather does try to autodetect the file format somehow based on the Xcode version, since Xcode 7.3.1 worked fine without the explicit format, but after I updated to Xcode 8.1 it got confused.

This might also be helpful for #249 and #250, but that's just a guess.

**Comment by manicmaniac** [comment]
Same here.
It fails even when I add `input_format: profdata` to `.slather.yml`.
However it works well when I add `--input-format profdata` as a command-line argument.

**Comment by ksuther** [comment]
Should be fixed by #298.
