### ISSUE TITLE
Generates the report for some of the Foundation class files

### ISSUE THREAD

**Issue by AnkitaSK** [SlatherOrg/slather#268]
I'm generating a report using the code mentioned below:
`slather coverage --show --scheme SchemaName --workspace WorkspaceName.xcworkspace ProjectName.xcodeproj`
The problem is that, it generates the report for some of the Foundation class files as well. I want to generate a report consisting only the project files.

![screen shot 2016-12-14 at 6 50 04 pm](https://cloud.githubusercontent.com/assets/6023419/21213674/1e391842-c2bc-11e6-8e5d-3608c185b818.png)

**Comment by bkbeachlabs** [comment]
You need to ignore those explicitly. Add `--ignore '../*'` to ignore everything outside of the root folder, for example. This will catch all of those.
