### ISSUE TITLE
Overall lines and function coverage data

### ISSUE THREAD

**Issue by Cyqlblgy** [SlatherOrg/slather#276]
Hi, thanks for this great repo, could someone tell me where to find the overall lines and function coverage data in HTML report, like what I use to get from the LCOV report  
![screen shot 2017-02-06 at 9 57 44 am](https://cloud.githubusercontent.com/assets/8834613/22652018/cffc877a-ec52-11e6-907c-e1d533baebf1.png)

**Comment by ksuther** [comment]
The index page of the HTML report will show you an overall line percentage.
