### ISSUE TITLE
Teamcity support when using upload to coveralls

### ISSUE THREAD

**Issue by joshrlesch** [SlatherOrg/slather#281]
Hi, I opened a PR to add TeamCity as a ci service in the Coveralls coverage service.

~~But Im having trouble not dropping the coverage %. I did add some unit tests, but still lowering it by .3%~~ Got the coverage up.

https://github.com/SlatherOrg/slather/pull/279

**Comment by joshrlesch** [comment]
Any of the maintainers have thoughts on this?

**Comment by ksuther** [comment]
It looks fine to me, ideally we'd get someone else who uses TeamCity to try it out as well.

Closing this in favor of the PR.
