### ISSUE TITLE
Code coverage is 0% when XCUITest executed with 'xcodebuild' command but works fine with XCode UI execution

### ISSUE THREAD

**Issue by vikaspune** [SlatherOrg/slather#282]
I am using slather to generate code coverage simple and static html report with Jenkins. 

Case 1: If I build project and run my XCUITests via XCode and then run slather command to generate report It shows correct coverage %.

Case 2: If I build and run tests using "xcodebuild" command (command line mode) then slather shows code coverage as 0.00% which is obviously wrong.

I am not sure what is exactly wrong in Case 2. below are the command I am using for building , testing and generating reports.

### Command to build and run tests ->
`xcodebuild clean -workspace iPhone.xcworkspace -scheme "iPhone - Flagship" -destination 'id=XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX' '-only-testing:TheAppUITests/ABCModuleTest -enableCodeCoverage YES test`

### Command to generate report
`slather coverage --html --scheme "iPhone - Flagship" --workspace iPhone.xcworkspace iPhone/iPhone.xcodeproj`

I have verified the `profdata.coverage` file is generated in **OBJROOT**
Just to check coverage from `profdata.coverage` file I have used 'llvm-cov' as below

`xcrun llvm-cov report -use-color=true -instr-profile ./Build/Intermediates/CodeCoverage/Coverage.profdata ./Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/TheWeather.app/TheWeather`

the result of llvm-cov and slather both are identical. that is 0% in case if I run tests from `xcodebuild`

This may not be a bug with slather as slather used the profdata.coverage file generated. And my observation is there is 0% code coverage in profdata.coverage when I run tests via xcodebuild command.

**Comment by jvsl** [comment]
I have the same issue. Any progress?

**Comment by ksuther** [comment]
This is a problem with xcodebuild rather than slather. Filing a bug report with Apple is probably the right thing to do here.
