### ISSUE TITLE
All files are 100% covered according to Slather

### ISSUE THREAD

**Issue by aeons** [SlatherOrg/slather#285]
Hey,

I have a project using Xcode 8.3 Beta 2. The project has working code coverage inside Xcode, but when slather is run on the output of xcodebuild, every single file has a coverage of 100%.

When I look at the detailed output per file, it seems that the only lines that are included are the ones that are covered by tests.

I don't know if this is caused by a change in format in the Xcode beta or something else.

Let me know what extra information could be useful to investigate this.

**Comment by aprilnov** [comment]
Same issue here, now it's not beta version..

**Comment by serges147** [comment]
Xcode 8.3 Release - same problem.

**Comment by ksuther** [comment]
Added Xcode 8.3 support in this PR: https://github.com/SlatherOrg/slather/pull/291

Feedback on whether it works would be appreciated.

**Comment by serges147** [comment]
With PR#291 works great! Thanks ksuther!
