### ISSUE TITLE
Coverage figure differs greatly from Xcode

### ISSUE THREAD

**Issue by bart-kneepkens** [SlatherOrg/slather#289]
When I run the full test suite in Xcode (unit, ui tests), a certain file has a coverage of 60,96 %. 

When I run the full test suite using Fastlane, and Slather afterwards, the Slather report shows the same file has a coverage of a mere 11,2 %. 

Does this have to do with Slather not taking into account UI tests, and Xcode doing so?

**Comment by ksuther** [comment]
UI tests aren't included in the coverage data written by Xcode.

**Comment by bart-kneepkens** [comment]
@ksuther are you sure? It seems to say so at https://developer.apple.com/library/content/documentation/DeveloperTools/Conceptual/testing_with_xcode/chapters/07-code_coverage.html 

`The code coverage option can collect data to report on tests of correctness and of performance, whether unit tests or UI tests.`

**Comment by ksuther** [comment]
What I mean is the standard coverage file written doesn't include the UI test coverage. There may be some separate place that Xcode is reading and writing coverage for UI tests, but it's not where the non-UI test coverage data is written.

**Comment by ksuther** [comment]
This is a bug in Xcode:

http://www.openradar.me/29033348

I've also filed a duplicate as 31322134.
