### ISSUE TITLE
Code coverage is wrongly showing 100% for all files

### ISSUE THREAD

**Issue by AamirSk** [SlatherOrg/slather#296]
Hi,
I have managed to generate code coverage report. But for all file it shows 100% coverage data. There are few files when I open them it shows blank file & some of them shows few lines of code. I believe code shown is actual code coverage which maps correctly with xcode code coverage report.
Any heads up on this?

I am using terminal command as below,

 `slather coverage -s --input-format profdata --binary-basename APP_NAME --scheme APP_Test --workspace ./app.xcworkspace ./app/app.xcodeproj`

On terminal it shows,
```
Slathering...
/Users/Aamir/.rvm/gems/ruby-2.4.0/gems/slather-2.3.0/lib/slather/project.rb:87: 
warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
```

& .slather.yml file is as below,
```
input_format: profdata
coverage_service: cobertura_xml
output_directory: test-reports
scheme: APP_Test
workspace: app.xcworkspace
xcodeproj: ./app/app.xcodeproj
ignore:
- ./app/Classes/CoreData/*
- ./app/Classes/ObjectModel/*
```
Also "test-reports" folder which is output directory folder added explicitly doesn't have any file after running command

**Comment by ksuther** [comment]
Please update to slather 2.4.0
