### ISSUE TITLE
XCode 8.3.1

### ISSUE THREAD

**Issue by serges147** [SlatherOrg/slather#297]
Slathering broken with xcode Version 8.3.1 (8E1000a)
Run with `slather coverage --verbose` command

`
Slathering...
/Users/sergei/.rvm/gems/ruby-2.3.3/gems/slather-2.4.0/lib/slather/project.rb:256:in `configure': undefined method `each' for nil:NilClass (NoMethodError)
	from /Users/sergei/.rvm/gems/ruby-2.3.3/gems/slather-2.4.0/lib/slather/command/coverage_command.rb:51:in `execute'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/gems/slather-2.4.0/bin/slather:17:in `<top (required)>'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/bin/slather:22:in `load'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/bin/slather:22:in `<main>'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sergei/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by ksuther** [comment]
It can't find any binaries. Are you explicitly setting binary_file in the configuration or are you letting it find them automatically?

**Comment by serges147** [comment]
Here is my .yml . Everything worked minute before upgrade of xcode.

`
coverage_service: cobertura_xml
workspace: mbam-mac-objc.xcworkspace
xcodeproj: mbam-mac-objc.xcodeproj
scheme: All_Unit_Tests
output_directory: build
verbose: true
ignore:
  - ../**/*/Xcode*
  - Pods/**
`

**Comment by serges147** [comment]
Debugging I see that `Slather.xcode_version` is null...  To be continued...

**Comment by ksuther** [comment]
PR incoming.

**Comment by serges147** [comment]
Yeah, there is no "kMDItemVersion" anymore in the .app

**Comment by ksuther** [comment]
I suspect it will eventually come back, but it's dependent on Spotlight. I've updated on two machines and Spotlight has caught up on the first one that updated, but not the second.

#298 will read directly from the Info.plist to avoid this entirely.

**Comment by serges147** [comment]
Cool!

**Comment by serges147** [comment]
BTW, `sudo mdls /Application/XCode.app` prints all the information ok, including kMDItemVersion. So I guess it depends on how you install XCode - I did it via mac App Store

**Comment by serges147** [comment]
Thank You @ksuther , with 2.4.1 release it's back working!
