### ISSUE TITLE
Unable to access coverage data from shared unit test target

### ISSUE THREAD

**Issue by varmeh** [SlatherOrg/slather#309]
I have a unit test target which holds all the coverage data.
Now, when I run following command
```
slather coverage --scheme AppUnitTests --workspace App.xcworkspace --binary-basename App App.xcodeproj
```
*I get coverage for app target & not for Unit Test target.*
How could I fix this?
Thank you for your help in advance

**Comment by ksuther** [comment]
Try not including `--binary-basename`. That's probably limiting the match to just the app itself.

**Comment by varmeh** [comment]
If I remove `--binary-basename`, i get following error:
`No product binary found in /Users/sg1obo/Library/Developer/Xcode/DerivedData/App-axyqhgvutemqzeabuszfzedhvpdl/Build/Intermediates/CodeCoverage`.

**Comment by ksuther** [comment]
Have you tried `--verbose` to see what paths slather is searching? Otherwise you might need to add some more logging to project.rb to figure out why it isn't finding it. You can also try `--binary-basename AppUnitTests` in addition to `--binary-basename App`.

**Comment by varmeh** [comment]
I see following paths with `--verbose`:
Coverage file `~/Library/Developer/Xcode/DerivedData/App-axyqhgvutemqzeabuszfzedhvpdl/Build/Intermediates/CodeCoverage/Coverage.profdata`
Binary files `~/Library/Developer/Xcode/DerivedData/App-axyqhgvutemqzeabuszfzedhvpdl/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/App.app/App`

If I change `--binary-basename` to `AppUnitTest`, I get the following error:

> No product binary found in /Users/userHome/Library/Developer/Xcode/DerivedData/App-axyqhgvutemqzeabuszfzedhvpdl/Build/Intermediates/CodeCoverage.

I have created a functional test target with [EarlGrey](https://github.com/google/EarlGrey).
Earlgrey uses `XCTest` for UI Testing.
When I run coverage for my functional test, I get _49.08%_ coverage, which is the correct value.

While for Unit Testing I am using [Quick](https://github.com/Quick/Quick).
Do I need some further configuration to get data with slather?

> I could see coverage data for my Unit test in XCode->Reports. It's there, but I am unable to fetch it with slather.

**Comment by Yahsaswi** [comment]
I'm also facing this error. Can someone please let me know of a working solution

**Comment by varmeh** [comment]
@Yahsaswi I know it's late but refer this [solution](https://github.com/SlatherOrg/slather/issues/312).
Worked for me
