### ISSUE TITLE
Failed to load coverage: Unknown architecture named

### ISSUE THREAD

**Issue by luisxiaomai** [SlatherOrg/slather#311]
Hi guy,

I used xcodebuild to do test and then run slather command to generate code coverage report, but met below issue:
```
slather coverage --build-directory /Users/xxx/test/test.ios/output --configuration Debug --scheme TestAnw --verbose --show src/xcode/anwstream.xcodeproj/
Slathering...

Processing coverage file: /Users/tester/testProject/test.ios/output/CodeCoverage/Coverage.profdata
Against binary files:
	/Users/tester/testProject/test.ios/output/CodeCoverage/Products/Debug-iphonesimulator/testiOS.app/testiOS

/Users/tester/testProject/test.ios/output/CodeCoverage/Products/Debug-iphonesimulator/testiOS.app/testiOS
: Failed to load coverage: Unknown architecture named: 
Test Coverage: NaN%
Slathered

```
Can someone help on this?

Thanks

**Comment by seanoshea** [comment]
I'm getting a very similar error:
```
[20:23:45]: ▸ Slathering...
[20:23:46]: ▸ error: /Users/sean.oshea/Library/Developer/Xcode/DerivedData/AWPSDK-gtqlseytzfqfkrglmdpoahamwgra/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/AWPSDK.framework/AWPSDK: Failed to load coverage: Unknown architecture named:
[20:23:46]: ▸ error: /Users/sean.oshea/Library/Developer/Xcode/DerivedData/AWPSDK-gtqlseytzfqfkrglmdpoahamwgra/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/AWPSDKTests.xctest/AWPSDKTests: Failed to load coverage: Unknown architecture named:
[20:23:46]: ▸ To open the html reports, use
[20:23:46]: ▸ open '/Users/sean.oshea/bb/ios_provider_sdk/AWPSDK/html/index.html'
[20:23:46]: ▸ or use '--show' flag to open it automatically.
[20:23:46]: ▸ Slathered
```

When I open the html report, I get `NaN`s in the report. I had a look through the slather source code for this error message, but couldn't find it anywhere? Maybe it's being generated from `xcodebuild` ?

FWIW, I'm getting this issue when building a iOS Framework which is linked to a static library. Both the static library and the framework have the exact same architectures and have `Build Active Architecture Only` set to false.

Using the `2.4.2` version of slather with ruby `2.4.1`. Happy to provide additional environment details if needed.

**Comment by seanoshea** [comment]
@luisxiaomai - I got around this issue by Only Building the Active Architecture for my `Debug` configuration.

**Comment by luisxiaomai** [comment]
@seanoshea,  It work with your information.

**Comment by seanoshea** [comment]
@luisxiaomai - great! Took me a while to figure this one out, but glad to get through it.

**Comment by swiftfoot** [comment]
That doesn't seem to work for me, I'm only building Active Architectures.  
<img width="725" alt="image" src="https://cloud.githubusercontent.com/assets/6663002/26469475/b61f825a-415f-11e7-9671-8627bc8b15b4.png">


Here's my specific output from slather:
Slathering...
error: <retracted>: Failed to load coverage: Unknown architecture named: 
error: <retracted>: Failed to load coverage: Unknown architecture named: 
Slathered

I also see the Code Coverage results successfully in my Report Navigator inside xcode.  any ideas

**Comment by am-a** [comment]
For those who find this later - I ended up needing to do: `xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=YES VALID_ARCHS=x86_64"`

**Comment by tirrorex** [comment]
Building active architectures only fixed it for me aswell

**Comment by ankit0409** [comment]
error: /Users/apple1/Library/Developer/Xcode/DerivedData/-cjsmveeyweoegccvtogoxdrcpgcy/Build/Products/Debug-iphonesimulator/-Runner.app/-Runner: Failed to load coverage: Unknown architecture named: 
error: Could not load coverage information
Traceback (most recent call last):
	16: from /Users/apple1/.rbenv/versions/2.6.6/bin/slather:23:in `<main>'
