### ISSUE TITLE
Slather giving incorrect coverage report for Unit test framework - Quick/nimble!

### ISSUE THREAD

**Issue by varmeh** [SlatherOrg/slather#312]
I am running on slather on coverage data.
`I could see test extensive test coverage in my coverage report.`
But slather gives me incorrect result with my Unit Test cases which are developed using [Quick](https://github.com/Quick/Quick) test framework.
Though I am getting correct result for XCTest.

>  Does slather works only for XCTest?

**Comment by ksuther** [comment]
slather will read whatever is in the coverage file. You can try running llvm-cov manually to see if that is showing coverage correctly.

`xcrun llvm-cov show -instr-profile /path/to/CodeCoverage/Coverage.profdata /path/to/YourXCTestBinary

**Comment by varmeh** [comment]
I am not sure how to access XCTestBinary?
Path to App binary is `~/Library/Developer/Xcode/DerivedData/App-axyqhgvutemqzeabuszfzedhvpdl/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/App.app/App`. 
I do see XCTestBundle in `Debug-iphonesimulator`. But no binary for it.

**Comment by ksuther** [comment]
Try looking inside your app bundle:

`Debug-iphonesimulator/MyApp.app/PlugIns/MyTests.xctest`

**Comment by varmeh** [comment]
Thank you so much. It worked finally.
