### ISSUE TITLE
nokogiri > 1.6.8 issue

### ISSUE THREAD

**Issue by dnedrow** [SlatherOrg/slather#324]
Currently, the nokogiri dependency version is set to >1.6. With that being the case, there may be an attempt to install a version of nokogiri >= 1.7. This will fail on all versions of MacOS, including Sierra, as the version of Ruby is not high enough.

Does slather use any features of nokogiri that are specific to >= 1.7? If not, I can submit a pull request to set nokogiri to either "1.6.8" or ">= 1.6", "< 1.7".

**Comment by ksuther** [comment]
Fixed by #326.
