### ISSUE TITLE
Ignore code coverage of a specific block

### ISSUE THREAD

**Issue by tapthaker** [SlatherOrg/slather#334]
While there is always an option to ignore code coverage of a file by adding it inside **.slather.yml** it would be a good enhancement to ignore code of a specific block. You could achieve it by adding comments before and after the block such as the following: 

```swift
//slather:ignore:start
print("Hello World")
let a = 2 + 3
//slather:ignore:end
```

**Comment by ppaulojr** [comment]
That would be awesome.
