### ISSUE TITLE
Xcode 8.3.3 `profdata_coverage_dir': No coverage directory found. (StandardError)

### ISSUE THREAD

**Issue by vijayviswas** [SlatherOrg/slather#335]
Hi,
I am using xcode 8.3.3. I get profdata folder not found the error when I execute below slather command.
`slather coverage -s --scheme TestUnit ./TestUnit.xcodeproj
`

I have noticed that profdata file is generated in below location.

/Users/user11/Library/Developer/Xcode/DerivedData/TestUnit-dcjuyahittebkhawjorhtxxvgqmr/CodeCoverage/Coverage.profdata

**Comment by saly2310** [comment]
You should run your test suite on your project before run slather command

**Comment by dnedrow** [comment]
If you're using a workspace, have you specified it in the slather.yml file?

I fought a similar problem for days, and finally figured out I had to specify the following in my config:

`build_directory: /Users/********/Library/Developer/Xcode/DerivedData/Foo-ejkjerhmnyggxjcwkahjencyggqe/Build
`

**Comment by ankitthakur** [comment]
But if we are deleting the DerivedData folder or are cleaning the build, then the build_directory will get changed.

**Comment by dnedrow** [comment]
@ankitthakur , I set the build_directory using a script to get the correct path.

Here's the pertinent part of that script...
`
# Find out the project temporary root
#####################################
echo ">>>>> Getting project configuration."
rm -f ${CONFIG_FILE}
xcodebuild -workspace ${WORKSPACE} -scheme ${SCHEME} -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' -configuration Debug -showBuildSettings  > ${CONFIG_FILE} 2> /dev/null
if [ ! -f ${CONFIG_FILE} ]; then
    echo ">>>>> Configuration file not found."
    echo ">>>>> Exiting"
    exit 0 # Don't "fail" the build
else
    echo ">>>>> Begin config file contents."
    cat ${CONFIG_FILE}
    echo ">>>>> End config file contents."
fi

PROJECT_TEMP_ROOT=$(grep -m1 PROJECT_TEMP_ROOT ${CONFIG_FILE} | cut -d= -f2 | xargs)
OBJROOT=$(grep -m1 OBJROOT ${CONFIG_FILE} | cut -d= -f2 | xargs)
BUILDDIR=$(echo ${OBJROOT} | rev | cut -d'/' -f2- | rev )
`

**Comment by vijayviswas** [comment]
This issue resolved after I specify --binary-file & --build-directory
