### ISSUE TITLE
--ignore folders

### ISSUE THREAD

**Issue by vijayviswas** [SlatherOrg/slather#343]
Hi All,
I am using below slather command and everything works fine except slather report contains thirdparty library headers.

`slather coverage --cobertura-xml --output-directory /Users/VV/Desktop/Report --scheme SharedSampleAppTests --workspace /Users/VV/Code/ios/Applications/SharedApp.xcworkspace --build-directory /Users/VV/Library/Developer/Xcode/DerivedData/ --verbose -s --ignore ‘*/ThirdPartyComponents/*’ /Users/VV/Code/ios/Applications/SharedApp/SharedApp/SharedApp.xcodeproj`

I tried adding  --ignore ‘*/ThirdPartyComponents/*’  but it doesn't work.

Below is the last few lines of output.
../../Code/ios/**ThirdPartyComponents**/OCMock/OCMock/OCMock.h: 20 of 20 lines (100.00%)
Test Coverage: 13.49%

**Comment by ksuther** [comment]
Try `--ignore ../../Code/ios/ThirdPartyComponents`

**Comment by vijayviswas** [comment]
@ksuther It worked 👍

**Comment by markph0204** [comment]
Other patterns that work...   `--ignore "**/*ViewController.swift"` as an example.

**Comment by Arunperfutil** [comment]
Hi all,
   I am using slather 2.7.1 version, when trying to exclude the third party libraries by running the following command it gets success but the xml file still has the reference of the SDK. Can someone please help me to remove the folders?

slather coverage --jenkins --ignore “./SDKs/*” --sonarqube-xml --build-directory ./Build --output-directory ./sonar-reports --scheme  Humm --workspace myProj.xcworkspace myProj.xcodeproj
