### ISSUE TITLE
Slather is Dependent on `xcode-select` for coverage path

### ISSUE THREAD

**Issue by dpfannenstiel** [SlatherOrg/slather#361]
Currently, Slather is dependent on running `xcode-select -p` to determine the location of the coverage data.  This complicates the use of slather in an environment where multiple versions of Xcode are required to support released applications under a long term SLA.

Add a flag `-x` or `--xcode-version` to indicated the version of Xcode to use.
Add a flag `-p` or `--coverage-path` to specify the path to the Coverage data.

**Comment by ksuther** [comment]
You can use the `DEVELOPER_DIR` environment variable before invoking slather to force it to use a specific version of Xcode. I think that will accomplish what you want.

**Comment by dpfannenstiel** [comment]
I'll certainly give that a try, however looking at the code on `master` I don't find that string literal in a case insensitive search.

Additionally, "BUILD_DIRECTORY" is documented as indicating where the "gcno" files are located.  I don't know what that is, but it looks like the use case will also allow the user to set the location of the profile data.

**Comment by ksuther** [comment]
`DEVELOPER_DIR` is part of xcode-select/Xcode, not slather, so that's why you don't see it mentioned.

You can use the build directory argument to point to where your derived data is, if you use a custom build path.

**Comment by dpfannenstiel** [comment]
Thanks, that solved my problem.  Deeply appreciate the quick responses.
