### ISSUE TITLE
Depends on vulnerable version of nokogiri

### ISSUE THREAD

**Issue by gnachman** [SlatherOrg/slather#363]
Github is warning users about nokogiri < 1.8.1. I got it because I depend on Slather, which specifies 

```
  spec.add_dependency 'nokogiri', '>= 1.6', '< 1.7'
```

in slather.gemspec.

**Comment by ksuther** [comment]
This is necessary so that slather can be installed on vanilla macOS (10.11 and 10.12). When I increased this dependency in the past people started running into trouble. This can change in the future once everyone has had a chance to transition to 10.13 (or 10.14, presumably).

**Comment by ksuther** [comment]
Fixed in f986a4600cd1372817c270db028131946a37ffa0
