### ISSUE TITLE
Swift test coverage.

### ISSUE THREAD

**Issue by nikita-leonov** [SlatherOrg/slather#39]
I know that there is no solution yet that allows to generate gcno for swift yet, but I would like to have this issue tracked separately to be alerted when it will be available in Slather. Thanks!

**Comment by jpsim** [comment]
Until Apple has official support for this, we've built https://github.com/realm/SwiftCov which might work for you in the meantime.

**Comment by nikita-leonov** [comment]
Amazing, thanks!

**Comment by neonichu** [comment]
This has been fixed by Xcode 7 and #92
