### ISSUE TITLE
Too many arguments with multiple parameters

### ISSUE THREAD

**Issue by MoonheadApps** [SlatherOrg/slather#391]
I am trying to run slather through the command line interface and I get the follow error `Too many arguments`

`slather coverage --html --scheme test-scheme --workspace test.xcworkspace test.xcodeproj --output-directory /Desktop/`

**Comment by ksuther** [comment]
Can you try `slather coverage --html --scheme test-scheme --workspace test.xcworkspace --output-directory /Desktop/ test.xcodeproj`?

**Comment by MoonheadApps** [comment]
Solution works above
