### ISSUE TITLE
Executing "bundle exec slather" fails

### ISSUE THREAD

**Issue by ch-one** [SlatherOrg/slather#403]
Calling `slather` **without** `bundle exec` works and creates the expected Cobertura XML file:
`slather coverage --input-format profdata --cobertura-xml --build-directory ./build --output-directory ./build/SlatherOutput --verbose --scheme Project --workspace ./Project.xcworkspace --decimals 2 Project/Project.xcodeproj`

On the other hand calling `slather` **with** `bundle exec` fails with `No coverage directory found.`.

What are we missing?
Any help is appreciated.

**Comment by MaikoHermans** [comment]
@ch-one for me the issue appears to have been that the bundle was running slather version 2.4.0 out of the box when running `bundle install` After I ran `bundle update` it seemed to work fine.

**Comment by ch-one** [comment]
Thanks @MaikoHermans.
Updating the gems helped.👌
