### ISSUE TITLE
When can we expect a new release?

### ISSUE THREAD

**Issue by abhimanyusirohi** [SlatherOrg/slather#422]
It has been more than 7 months since the last 2.4.6 release. Is there an approx date when we can expect the new version to be released?

**Comment by Trane9991** [comment]
There is [2.4.7](https://github.com/SlatherOrg/slather/blob/master/CHANGELOG.md#v247) release in the CHANGELOG but it was never released as GEM or even GitHub release.

@ksuther we need your help here.

**Comment by ksuther** [comment]
Sorry for the delay, done!
