### ISSUE TITLE
XCode 11.4 issue

### ISSUE THREAD

**Issue by sanalms** [SlatherOrg/slather#457]
The code coverage shows wrong values after upgrading to Xcode 11.4. Xcode shows 63% coverage but in slather report it's just 2%. Please let me know is there any way to fix it.

**Comment by e911miri** [comment]
Can you share more information?

**Comment by OllaAshour** [comment]
@sanalms Have you been able to resolve this?

**Comment by JensK611** [comment]
@sanalms I had the same problem. Deleting the projects derived data folder solved the issue for me.

**Comment by sanalms** [comment]
Thanks everyone. I have not tried much on this issue, switched my CI server to xCode 11.3 and it is working fine.
