### ISSUE TITLE
Support Github Actions

### ISSUE THREAD

**Issue by dunyakirkali** [SlatherOrg/slather#458]
Would it be possible to support GithubActions and Coveralls?

https://github.com/SlatherOrg/slather/blob/69b74115aa3e0166230332e548d81aaeb669c973/lib/slather/coverage_service/coveralls.rb

**Comment by senmu** [comment]
This appears to have been addressed in #468

**Comment by ksuther** [comment]
It is. 2.6.0 still needs to go out (I'm fighting with CI still), but it will go out soon.
