### ISSUE TITLE
Can I get coverage data from *.xcresult not from Coverage.profdata?

### ISSUE THREAD

**Issue by jay0129** [SlatherOrg/slather#462]
It looks like Slather gets coverage data from `Coverage.profdata`.
However, I want to get coverage data from *.xcresult.

To explain the reason.
I run those kinds of test in parallel:
```
xcodebuild test-without-building -derivedDataPath "derivedData" -resultBundlePath TestResults1
xcodebuild test-without-building -derivedDataPath "derivedData" -resultBundlePath TestResults2
```
and then, merge many TestResults into `TestResultMerged.xcresult`
In this way I can merge coverage data into single format.

However, I couldn't find how to save Coverage.profdata for each tests and merge eventually.

**Comment by aelam** [comment]
try this 
https://community.sonarsource.com/t/coverage-test-data-generate-reports-for-swift/9700
