### ISSUE TITLE
Migrate slather for Ruby 2.7.0

### ISSUE THREAD

**Issue by kelianClerc** [SlatherOrg/slather#464]
Hi,

Is it possible to update Slather to be used with Ruby 2.7.0 ?
When trying to use the gem with that ruby version I've got the following error :
`undefined method new for BigDecimal:Class`

It seems to come from `activesupport` gem for which versioning requirements are `'< 5', '>= 4.0.2'`

Thanks,
Kélian

**Comment by ksuther** [comment]
Should be fixed by #467
