### ISSUE TITLE
Contains the source of the libraries managed by SwiftPM

### ISSUE THREAD

**Issue by uhooi** [SlatherOrg/slather#475]
## Overview

Contains the source of the libraries managed by Swift Package Manager(SwiftPM).
Is there any way to ignore it?

## Environments

- Xcode: 12.3
- Ruby: 2.7.1
- Bundler: 2.1.4
- Slather: 2.6.1

## Screenshots

Firebase sources are included.

<img width="1074" alt="スクリーンショット 2021-02-12 23 20 32" src="https://user-images.githubusercontent.com/21194714/107779608-f3e84f00-6d88-11eb-8d78-7e1363b15790.png">

**Comment by uhooi** [comment]
I should just ignore the `SourcePackages` folder.
I'll find a way to ignore it.

<img width="1604" alt="スクリーンショット_2021-02-13_9_49_31" src="https://user-images.githubusercontent.com/21194714/107836834-ce3b6400-6de1-11eb-91ae-597fdd6642fb.png">

**Comment by msaps** [comment]
@uhooi I resolved this by ignoring the offending SPM directories in my `.slather.yml` suggested in #445 - specifically [this](https://github.com/SlatherOrg/slather/issues/445#issuecomment-614732663)

**Comment by uhooi** [comment]
This issue is a duplicate of #445, so it is closed.

**Comment by uhooi** [comment]
@msaps 
Thank you very much :)
I ignored the `../../../../../Library/Developer/Xcode/DerivedData/*` and it was OK.
https://github.com/uhooi/UhooiPicBook/commit/5f2038a6bc24e813a33a5841bf53dd15f2283910

Example of a library path managed by SwiftPM:

```
../../../../../Library/Developer/Xcode/DerivedData/UhooiPicBook-xxxxxxxxxxxxxxxxxxxxxxxxxxxx/SourcePackages/checkouts/firebase-ios-sdk/FirebaseAppDistribution/Sources/FIRAppDistribution.m
```

**Comment by uhooi** [comment]
CI fails for relative paths.
I fixed it as follows.
https://github.com/uhooi/UhooiPicBook/commit/a14031e09331b65f703a59a56fffb45191bd29e6
