### ISSUE TITLE
Xcode 13 M1 - No coverage directory found.

### ISSUE THREAD

**Issue by robinhayward** [SlatherOrg/slather#509]
Hello, I've not used slather for a while but just tried to run it against a sample project however it fails with "No coverage directory found."

Xcode 13.2.1, M1 Mac, 'Gather Coverage Data' enabled on the Test scheme.

Feels like a common problem as everything here is vanilla, has anyone else experienced this? The fact it's not common leads me to believe I may be missing something obvious 😅

Logs -----------------------

Slathering...
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
	If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)

bundler: failed to load command: slather (/usr/local/bin/slather)
/Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/project.rb:239:in `profdata_coverage_dir': No coverage directory found. (StandardError)
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/project.rb:517:in `find_binary_files'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/project.rb:456:in `configure_binary_file'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/project.rb:336:in `configure'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/lib/slather/command/coverage_command.rb:59:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
	from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/slather-2.7.2/bin/slather:17:in `<top (required)>'
	from /usr/local/bin/slather:23:in `load'
	from /usr/local/bin/slather:23:in `<top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli/exec.rb:23:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:484:in `exec'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:31:in `dispatch'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/cli.rb:25:in `start'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Library/Ruby/Gems/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
	from /usr/local/bin/bundle:23:in `load'
	from /usr/local/bin/bundle:23:in `<main>'

**Comment by robinhayward** [comment]
This ticket can be closed, as suspected it was something obvious.. adjusting the build folder in the project/workspace settings resolved this.

**Comment by salvatoreboemia** [comment]
> This ticket can be closed, as suspected it was something obvious.. adjusting the build folder in the project/workspace settings resolved this.

Hi, I have same issure, how exactly did you solve it? 

Thanks
