### ISSUE TITLE
would it be possible to make a new release?

### ISSUE THREAD

**Issue by paulz** [SlatherOrg/slather#526]
thank you for Slather project and maintaining it!

We have been using it every day and pin the version to master, but that cause our bundler to check for new commits and trigger updates when not necessary.

If we can have a release of 2.7.3 then our bundler will be happier.

Thank you!

**Comment by ksuther** [comment]
Thanks for the nudge, I'll push an update soon.

**Comment by ksuther** [comment]
Just released 2.7.3.
