### ISSUE TITLE
New version number

### ISSUE THREAD

**Issue by getaaron** [SlatherOrg/slather#551]
Now that @jarrodlombardo-EventBase's PR https://github.com/SlatherOrg/slather/pull/550 is merged, we'd like to support it in _fastlane_: https://github.com/fastlane/fastlane/pull/21613

Merging this PR is blocked on knowing the correct version of slather to assign it to. Do you know if it will be 2.8.0 or 2.7.6 or something else? Is it possible to cut a new version now?

**Comment by jarrodlombardo-EventBase** [comment]
If this followed SemVer, it should be 2.8.0, but the changelog seems to show a pattern of not following SemVer and adding features in patch releases (so maybe this will be 2.7.6). Either way, we need a release for Fastlane to take the change. cc @ksuther

Thanks :)

**Comment by ksuther** [comment]
Done! I keep bumping the patch version out of habit, went to 2.8.0 this time :)
