### ISSUE TITLE
Can we get a 2.8.1 release?

### ISSUE THREAD

**Issue by dnedrow** [SlatherOrg/slather#560]
I had a PR merged that enhanced the blob handling for includes/excludes.

@ksuther Could you create a 2.8.1 release with this change?

Also, if you want help with the repo, I'd be glad to chip in my time. Maybe clean up a bunch of stale issues, review PRs, etc.

-David

**Comment by ksuther** [comment]
Thanks, I'll cut a release in the next few days.

I somehow unwittingly ended up as the de facto maintainer of slather (and honestly don't particularly want to be at this point), so any assistance is definitely appreciated!

**Comment by ksuther** [comment]
Done!

**Comment by jarrodlombardo-EventBase** [comment]
@ksuther I can also be a helper with this. I might not be able to actually fix things often, but definitely available to review PRs and cut releases. Please invite my personal account ([@jarrodlombardo](https://github.com/jarrodlombardo)) so I can still help if I change jobs in the future.

**Comment by ksuther** [comment]
Thanks for the offer! I don't have permission to modify the slather org to make anything official, that's something @ayanonagon or @neonichu would need to do.

**Comment by jarrodlombardo** [comment]
@ayanonagon @neonichu please add @dnedrow and me as maintainers since @ksuther can't add us.
