### ISSUE TITLE
2.8.0 - sonarqube_xml through fastlane is failing to slather and there is no report generated and empty

### ISSUE THREAD

**Issue by cah-iswaria-sasi** [SlatherOrg/slather#562]
This is what i am getting for sonarqube_xml format:

sonarqube-generic-coverage.xml: report is empty. i have verified .profdata nd binary files are generating properly under each packages. earlier was using 2.7.5 slather, was working fine.. suddenly it stopped working.

means, .xml file is empty .
i am using slather 2.8.0
fastlane 2.221.1
ruby 3.3.3
bundler 2.5.13
xcode version 15.0.1
macos - sonoma 14.5

sometimes its working fine in my local, can see .xml fine.. i have upgraded versions on Build Machine (Mac) same to my local , but in BM its not working as expected. .xml file is empty

sonarqube_xml, its failing to generate .xml file for coverage

**Comment by jarrodlombardo-EventBase** [comment]
Please add the Slather part of your fastlane console output. I know other people have sonarqube working with slather 2.8.0 so we need to figure out what's different/going wrong for you.

**Comment by cah-iswaria-sasi** [comment]
log is clean, no errors reported.

i can see slather is doing its work but observed sonarqube.xml file is empty with no data

eg:

o/p in fastlane log

[19:56:30]: ---------------------
[19:56:30]: --- Step: slather ---
[19:56:30]: ---------------------
[19:56:30]: $ slather coverage --jenkins --sonarqube-xml --build-directory ./Packages/Account/DerivedData --source-directory ./Packages/Account/Sources --output-directory ./sonar-reports/Account --verbose --scheme Vantus --binary-basename Account.o ./XXX.xcodeproj
[19:56:31]: ▸ Slathering...
[19:56:33]: ▸ Processing coverage file: /Users/iswaria.sasi/Documents/sourcecode/projectXXXX/Packages/Account/DerivedData/Account/Build/ProfileData/7C717D9C-73E8-453A-9028-13E27FCDC35B/Coverage.profdata
[19:56:33]: ▸ Against binary files:
[19:56:33]: ▸ /Users/iswaria.sasi/Documents/sourcecode/projectXXXX/Packages/Account/DerivedData/Account/Build/Products/Debug-iphonesimulator/Account.o
[19:56:33]: ▸ Slathered

**Comment by cah-bhavesh-lathigara** [comment]
Hello 
I am getting the same issue.
I have tried with updating all the latest the versions of Slather.
I have tried installing XCode 15.4 since 15.2 was not available.
But still slather is generating report with empty sonarqube_xml data.
Kindly look into this on urgent basis?

**Comment by cah-iswaria-sasi** [comment]
i Just verified the .xcresult file generated after test and i can able to see the coverage % in it.

not sure why slather is generating empty **sonarqube-generic-coverage.xml** file (46 bytes)

**Comment by cah-iswaria-sasi** [comment]
can we have any update here

**Comment by cah-iswaria-sasi** [comment]
This issue is resolved, i upgraded the MacOS from sonoma 14.1.1 to 14.5 and fixed the issue.. slather started generating coverage xml files for sonarqube-generic-coverage.xml format. Hope this information helps for anyone who is going through this issue.

issue :
slather 2.8.0
fastlane 2.221.1
ruby 3.3.3
rubygems 3.5.13
bundler 2.5.13
xcode version 15.0.1
macos - sonoma 14.5

**Comment by cah-iswaria-sasi** [comment]
closing this issue @ksuther @jarrodlombardo-EventBase

**Comment by jarrodlombardo-EventBase** [comment]
I'm glad this resolved, but what changed with your upgrade? My guess is your DerivedData folder moved or something else controlled by MacOS or XCode changed, but do you have any idea what it was?

**Comment by cah-iswaria-sasi** [comment]
@jarrodlombardo-EventBase i am actually not sure what was the exact issue. i switched back to the old versions when it was working fine with latest macos 14.5. it worked.. but issue still persists with newer versions... somewhere ther is discrepency.

in my Local, which had newer versions for everything is working perfectly fine... but same thing on Old version Macos/Ruby/bundler it wasnt working.
please try to fix the discrepency in old and same versions.. we shall need to update newer versions anytime soon.

**Comment by jarrodlombardo-EventBase** [comment]
That's just it though; the issue is something in your system (OS, Env, something), not Slather. Without knowing what is going wrong with the system, we can't modify Slather to try to work around whatever is changing in your system.
