### ISSUE TITLE
Add --verbose option

### ISSUE THREAD

**Issue by ayanonagon** [SlatherOrg/slather#71]
Suggestion from @marklarr:

* Log when we've successfully configured pods for slather
* Log each GCNO file that is ignored (ones for files that aren't your source files, and also duplicate ones.)
* Log each GCNO file that is processed, along with its
* created_at timestamp
* modified_at timestamp
* Contents? Seems too noisy... but it'd be nice to at least see a couple.
* Add some sort of #inspect method to Slather::CoverageFile class, and print out this as well.
* Add coverage_service specific logging to each of the services. For example, for coveralls, print out the JSON blob that it'll send to coveralls, and the response from coveralls after it has been posted.

**Comment by JamieREvans** [comment]
I agree. Whenever I'm having trouble with my Travis CI's slather, it would be really helpful to have a breakdown of what's going on so I can see where it's failing.

**Comment by JamieREvans** [comment]
I agree. I'd love to get a breakdown of where slather is failing for my repositories. What I'm getting right now isn't quite helping:

```
$ slather
Slathering...
Slathered
```

**Comment by kdawgwilk** [comment]
:+1:

**Comment by viteinfinite** [comment]
This feature has already been implemented in slather's 2.0 version but it only supports the `profdata` format.

**Comment by neonichu** [comment]
I feel like this should be enough for now, since most people will be using Xcode 7 going forward. If anyone wants to contribute verbose output for gcov, I'd be more than happy to merge a PR, though.
