### ISSUE TITLE
Support Codecov

### ISSUE THREAD

**Issue by stevepeak** [SlatherOrg/slather#81]
Hey friends,

I'm the founder of [Codecov](https://codecov.io) and would like to accept uploads from Slather. I simply need an example output file I can parse into our format on Codecov.

Thank you for your time!

**Comment by marklarr** [comment]
Hey, thanks for supporting slather! 

Slather exports to many different outputs, which can be found here https://github.com/venmo/slather/tree/master/lib/slather/coverage_service. Users can control which output slather uses by passing in a flag.

What I would suggest is making a new `coverage_service` for Codecov, and copying how `coveralls` or one of the other coverage services work. I can help with that part.

If you want to accept JSON that looks a little different than Coveralls', we can make those changes. I can help with the Ruby side if you need anything.

**Comment by JamieREvans** [comment]
I'm currently trying to integrate using Travis / Cocoapods / Slather / Codecov and came across this. I'd love it if you could make the coverage service for slather, otherwise I will have to switch to Coveralls; Cocoapods don't play well with the existing suggestion (https://github.com/codecov/example-xcode).

**Comment by stevepeak** [comment]
@JamieREvans what is the repo you are having issues with? I would like to help you out. Thanks!

**Comment by RyanCopley** [comment]
@jamierevans the example project shows you how to set codecov on Travis, the example app is just to show you that it works. Could you please clarify?

**Comment by JamieREvans** [comment]
@RyanCopley  The setup assumes that the code your tests cover are associated with your .xcodeproj, which is not the case for cocoapods. An example is https://github.com/JamieREvans/NetworkSimple. I've used the Travis / Slather stack to generate the correct code coverage for my cocoapod.

@stevepeak The repository that I'm having trouble with is private, but an example could be https://github.com/JamieREvans/NetworkSimple. I need to use the Travis / Slather stack to generate the correct code coverage files; specifically the ones in Pod/Classes/**/*{.m}. Simply generating Xcode Project based coverage isn't correct.

**Comment by RyanCopley** [comment]
> Simply generating Xcode Project based coverage isn't correct.

I think what you mean is that it isn't what you need. Project based coverage is very useful for other styles of projects.

I don't have much experience writing Cocoapods, but why can't you add your Cocoapod's files to your xcodeproj? I've never done this so bare with me-- I'm sure there is a solution here somewhere, if it's slather or not.

**Comment by RyanCopley** [comment]
and @JamieREvans - On a completely unrelated sidenote, I looked deeper in your project, and with how you're writing your tests, might I recommend https://github.com/dstnbrkr/VCRURLConnection over OCMock? It's a better way to test http requests :)

Cheers

**Comment by JamieREvans** [comment]
@RyanCopley I definitely appreciate that `xcodeproj` based coverage is very useful in most cases, but in the case of cocoapods, where the files cannot be added to the `xcodeproj` (The example app for the pod), but must be installed to an `xcworkspace` under a generated 'Pods' `xcodeproj` (see 'pod install'). That being said, any code coverage generated for the `xcodeproj` will not include the cocoapod classes, but will include the coverage of the source in the example project, instead.

There is something about the way Travis and Slather work together that it is able to generate and only capture the pod coverage files.

**Comment by JamieREvans** [comment]
@RyanCopley I'll definitely take a look. For the most part, I'm used to stubbing callbacks for any asynchronous tests, so I decided to use that method for my network tests, as well.

**Comment by RyanCopley** [comment]
Why can't you pass `-workspace` instead of `-project` to xctool? That should work to my knowledge?

**Comment by JamieREvans** [comment]
@RyanCopley That would work, but how would you upload only the cocoapod file's gcda files?

**Comment by RyanCopley** [comment]
Specify them to be ignored in the Codecov Web UI like so: 

![screen shot 2015-05-29 at 1 52 03 am](https://cloud.githubusercontent.com/assets/819591/7877217/5664322c-05a5-11e5-9c24-3131656c7238.png)

**Comment by marklarr** [comment]
If you're trying to get the coverage of a Pod, you can use the Cocoapods Slather plugin. Does that help?

**Comment by marklarr** [comment]
Where is this issue at?

**Comment by stevepeak** [comment]
> @RyanCopley helped @JamieREvans on an issue, Thank you!

The primary purpose of this issue is to integrate Slather into Codecov. From your [comment above](https://github.com/venmo/slather/issues/81#issuecomment-102545338) I would prefer to see Codecov be added to `coverage_service`. 

However, simply adding Codecov to the readme will work if the user outputs a [cobertura report](https://github.com/venmo/slather#cobertura) and follows the directions on our [Global Uploader](https://github.com/codecov/codecov-bash) which will find all reports and upload them to Codecov.


> As for the format of the json we have a [api guide](https://codecov.io/api#post-report) on uploading reports. Supp

**Comment by tabuchid** [comment]
One caveat using the global uploader vs a full integration as a `coverage_service` is the global uploader will look for all coverage files meaning if you add ignores in your `.slather.yml` they won't get recognized by the global uploader.

**Comment by stevepeak** [comment]
@tabuchid If this becomes an issue then I would like to add a method parse the .slather.yml file and ignore the files accordingly. 

Within Codecov UI there is an Ignore Paths which can be setup in the case of extra reports showing up.

**Comment by tabuchid** [comment]
If you want the ignore files to be respected you have to make the uploader read the report output by slather.
Here is a sample from my circle.yml
```
test:
    override:
        - xctool
          -reporter pretty
          -reporter junit:$CIRCLE_TEST_REPORTS/xcode/results.xml
          -reporter plain:$CIRCLE_ARTIFACTS/xctool.log
          CODE_SIGNING_REQUIRED=NO
          CODE_SIGN_IDENTITY=
          PROVISIONING_PROFILE=
          GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES
          GCC_GENERATE_TEST_COVERAGE_FILES=YES
          -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
          -sdk iphonesimulator
          -workspace $XCODE_WORKSPACE
          -scheme $XCODE_SCHEME
          build build-tests run-tests
    post:
        - bundle exec slather coverage --output-directory $CIRCLE_ARTIFACTS/coverage_reports/ && ./script/codecov -f $CIRCLE_ARTIFACTS/coverage_reports/cobertura.xml
```

**Comment by neonichu** [comment]
Closing, since this has been inactive for a while.
