### ISSUE TITLE
Support Xcode 7's code coverage mapping format

### ISSUE THREAD

**Issue by Ashton-W** [SlatherOrg/slather#89]
We should look into supporting the *LLVM’s code coverage mapping format*.

http://llvm.org/docs/CoverageMappingFormat.html
http://llvm.org/docs/CommandGuide/llvm-profdata.html
http://llvm.org/docs/CommandGuide/llvm-cov.html

Xcode uses LLVM, one day it might encourage developers to use this coverage format too.

---

Xcode 7 compiles this data together into a binary plist with the extension `.xccoverage`, reading that should be much easier.

**Comment by viteinfinite** [comment]
I have just submitted the PR #92, adding experimental support to the new format. It should work for both ObjC and Swift. Hope that helps!

**Comment by yakimant** [comment]
Hi guys! Should i try #92 or #99?

**Comment by danthorpe** [comment]
Hi @yakimant! How you doing? 

I'm trying to add support for test coverage reports in CI for a project. Just wondering if you've had any progress with Slather?

**Comment by yakimant** [comment]
Hi @danthorpe!

We are trying llvm-cov show + filter + some scripting for now, as we need the overall numbers.
As for slather - will use it as it is at least in master)

**Comment by danthorpe** [comment]
Okay, that's interesting thanks @yakimant. I'll looking into llvm-cov - is your codebase still primarily Objective-C? I'm trying to get coverage reports in CI for (https://github.com/danthorpe/Operations) a Swift 2.0 / Xcode 7 project.

**Comment by Cocoanetics** [comment]
@yakimant I have published this Swift open source project today and would like to get code coverage for it: https://travis-ci.org/Cocoanetics/Kvitto

**Comment by patdnk** [comment]
Merges from viteinfinite & mattdelves branches would be really beneficial for new profdata crunching.
There are still issues with some cobertura reports, but merges must come first.

**Comment by daniel-beard** [comment]
Is this one now done through #92 ?

**Comment by patdnk** [comment]
No as far as I know. In general slather is off on calculations (i.e.: conditionals are completely screwed up on cobertura).

None of the branches implemented multi parameter ignore which seems to be vital part for projects including cocoa pods. Without it you ignore Xcode artefacts or pods, either way code coverage report will be way off on what you should actually see.

Would be nice to bump the project and do the Jenkins driven alternative to completely crapped 5.0.15 OS X Server when it comes to code coverage.

**Comment by neonichu** [comment]
Even though there might still be bugs, the original goal of the issue has been implemented with #92. Please open concrete individual issues for other problems you are seeing.
